-- [AUTH_CORE_TABLE_STATUS]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN (
       'INIT$_TB_USER'
     , 'INIT$_TB_AUTH_SESSION'
     , 'INIT$_TB_NOTICE'
     , 'INIT$_TB_NOTICE_FILE'
 )
;

-- [AUTH_USER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
;

-- [AUTH_CORE_COLUMN_STATUS]
SELECT TABLE_NAME
     , COLUMN_NAME
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN (
       'INIT$_TB_USER'
     , 'INIT$_TB_AUTH_SESSION'
     , 'INIT$_TB_NOTICE'
     , 'INIT$_TB_NOTICE_FILE'
 )
;

-- [AUTH_FIRST_ADMIN_LOCK]
LOCK TABLE "INIT$_TB_USER" IN EXCLUSIVE MODE
;

-- [AUTH_SIGNUP_DUPLICATE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE LOGIN_ID = :loginId
    OR LOWER(EMAIL) = LOWER(:email)
;

-- [AUTH_SIGNUP_INSERT_USER]
INSERT INTO "INIT$_TB_USER" (
    LOGIN_ID
  , USER_NAME
  , EMAIL
  , PASSWORD_HASH
  , ROLE_CODE
  , USE_YN
  , PASSWORD_CHANGE_YN
  , CREATED_AT
) VALUES (
    :loginId
  , :userName
  , :email
  , :passwordHash
  , :roleCode
  , :useYn
  , 'Y'
  , SYSTIMESTAMP
)
;

-- [AUTH_LOGIN_USER]
SELECT USER_ID
     , LOGIN_ID
     , USER_NAME
     , EMAIL
     , PASSWORD_HASH
     , USE_YN
     , ROLE_CODE
     , PASSWORD_CHANGE_YN
  FROM "INIT$_TB_USER"
 WHERE LOGIN_ID = :loginId
;

-- [AUTH_SESSION_INSERT]
INSERT INTO "INIT$_TB_AUTH_SESSION" (
    SESSION_TOKEN_HASH
  , USER_ID
  , CREATED_AT
  , LAST_SEEN_AT
  , EXPIRES_AT
) VALUES (
    :sessionTokenHash
  , :userId
  , LOCALTIMESTAMP
  , LOCALTIMESTAMP
  , LOCALTIMESTAMP + NUMTODSINTERVAL(:ttlSeconds, 'SECOND')
)
;

-- [AUTH_SESSION_SELECT]
SELECT U.USER_ID
     , U.LOGIN_ID
     , U.USER_NAME
     , U.EMAIL
     , U.ROLE_CODE
     , U.PASSWORD_CHANGE_YN
  FROM "INIT$_TB_AUTH_SESSION" S
  JOIN "INIT$_TB_USER" U
    ON U.USER_ID = S.USER_ID
 WHERE S.SESSION_TOKEN_HASH = :sessionTokenHash
   AND S.REVOKED_AT IS NULL
   AND S.EXPIRES_AT > LOCALTIMESTAMP
   AND U.USE_YN = 'Y'
;

-- [AUTH_SESSION_TOUCH]
UPDATE "INIT$_TB_AUTH_SESSION"
   SET LAST_SEEN_AT = LOCALTIMESTAMP
     , EXPIRES_AT = LOCALTIMESTAMP + NUMTODSINTERVAL(:ttlSeconds, 'SECOND')
 WHERE SESSION_TOKEN_HASH = :sessionTokenHash
   AND REVOKED_AT IS NULL
;

-- [AUTH_SESSION_REVOKE]
UPDATE "INIT$_TB_AUTH_SESSION"
   SET REVOKED_AT = LOCALTIMESTAMP
 WHERE SESSION_TOKEN_HASH = :sessionTokenHash
   AND REVOKED_AT IS NULL
;

-- [AUTH_SESSION_DELETE_EXPIRED]
DELETE
  FROM "INIT$_TB_AUTH_SESSION"
 WHERE EXPIRES_AT <= LOCALTIMESTAMP
    OR REVOKED_AT IS NOT NULL
;
