-- [HOME_DASHBOARD_COUNTS]
SELECT (
       SELECT COUNT(*)
         FROM "INIT$_TB_USER"
       ) AS USER_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_USER"
        WHERE USE_YN = 'Y'
       ) AS ACTIVE_USER_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_NOTICE"
        WHERE USE_YN = 'Y'
          AND (POST_START_AT IS NULL OR POST_START_AT <= SYSTIMESTAMP)
          AND (POST_END_AT IS NULL OR POST_END_AT >= SYSTIMESTAMP)
       ) AS NOTICE_COUNT
  FROM DUAL
;

-- [HOME_ACTIVE_NOTICES]
SELECT NOTICE_ID
     , NOTICE_TYPE
     , TITLE
     , CONTENT
     , POST_START_AT
     , POST_END_AT
     , PIN_YN
     , SORT_ORDER
     , FILE_COUNT
     , CREATED_AT
  FROM (
        SELECT N.NOTICE_ID
             , N.NOTICE_TYPE
             , N.TITLE
             , N.CONTENT
             , N.POST_START_AT
             , N.POST_END_AT
             , N.PIN_YN
             , N.SORT_ORDER
             , (
                SELECT COUNT(*)
                  FROM "INIT$_TB_NOTICE_FILE" F
                 WHERE F.NOTICE_ID = N.NOTICE_ID
                   AND F.USE_YN = 'Y'
               ) AS FILE_COUNT
             , N.CREATED_AT
          FROM "INIT$_TB_NOTICE" N
         WHERE N.USE_YN = 'Y'
           AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
           AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP)
         ORDER BY N.PIN_YN DESC
                , N.SORT_ORDER
                , N.CREATED_AT DESC
       )
 WHERE ROWNUM <= :limit
;

-- [HOME_EXECUTIVE_PROJECT_SUMMARY]
SELECT COUNT(*) AS PROJECT_COUNT
     , SUM(CASE WHEN STATUS_CODE IN ('PLANNED', 'BIDDING') THEN 1 ELSE 0 END) AS BID_TARGET_COUNT
     , SUM(CASE WHEN STATUS_CODE IN ('CONTRACTED', 'IN_PROGRESS', 'COMPLETED') THEN 1 ELSE 0 END) AS AWARDED_COUNT
     , NVL(SUM(ORDER_AMOUNT_VAT), 0) AS ORDER_AMOUNT_VAT
     , NVL(SUM(CONTRACT_AMOUNT_VAT), 0) AS CONTRACT_AMOUNT_VAT
  FROM "INIT$_TB_PROJECT"
 WHERE 1=1
   AND PROJECT_YEAR = :planYear
   AND STATUS_CODE <> 'CANCELLED'
;

-- [HOME_EXECUTIVE_WORKFORCE_SUMMARY]
SELECT (
       SELECT COUNT(*)
         FROM "INIT$_TB_USER" U
        WHERE U.USE_YN = 'Y'
          AND U.EMPLOYMENT_STATUS_CODE <> 'RETIRED'
          AND (U.HIRE_DATE IS NULL OR U.HIRE_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD'))
          AND (U.RETIREMENT_DATE IS NULL OR U.RETIREMENT_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD'))
       ) AS INTERNAL_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_COMPANY_EMPLOYEE" E
         JOIN "INIT$_TB_COMPANY" C
           ON C.COMPANY_ID = E.COMPANY_ID
        WHERE E.USE_YN = 'Y'
          AND C.USE_YN = 'Y'
          AND C.COMPANY_TYPE_CODE = 'PARTNER'
          AND (E.JOIN_DATE IS NULL OR E.JOIN_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD'))
          AND (E.LEAVE_DATE IS NULL OR E.LEAVE_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD'))
       ) AS PARTNER_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_COMPANY_EMPLOYEE" E
         JOIN "INIT$_TB_COMPANY" C
           ON C.COMPANY_ID = E.COMPANY_ID
        WHERE E.USE_YN = 'Y'
          AND C.USE_YN = 'Y'
          AND C.COMPANY_TYPE_CODE = 'FREELANCER'
          AND (E.JOIN_DATE IS NULL OR E.JOIN_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD'))
          AND (E.LEAVE_DATE IS NULL OR E.LEAVE_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD'))
       ) AS FREELANCER_COUNT
  FROM DUAL
;

-- [HOME_EXECUTIVE_LATEST_SCENARIO]
SELECT SCENARIO_ID
  FROM (
        SELECT S.SCENARIO_ID
          FROM "INIT$_TB_PLAN_SCENARIO" S
         WHERE 1=1
           AND S.PLAN_YEAR = :planYear
         ORDER BY CASE S.STATUS_CODE WHEN 'DRAFT' THEN 1 WHEN 'CONFIRMED' THEN 2 ELSE 3 END
                , NVL(S.UPDATED_AT, S.CREATED_AT) DESC
                , S.SCENARIO_ID DESC
       )
 WHERE ROWNUM = 1
;

-- [HOME_EXECUTIVE_DECISION_PROJECTS]
SELECT PROJECT_ID
     , PROJECT_NAME
     , CUSTOMER_NAME
     , STATUS_CODE
     , ORDER_AMOUNT_VAT
     , CONTRACT_AMOUNT_VAT
     , TO_CHAR(PROJECT_START_DATE, 'YYYY-MM-DD') AS PROJECT_START_DATE
     , TO_CHAR(PROJECT_END_DATE, 'YYYY-MM-DD') AS PROJECT_END_DATE
  FROM (
        SELECT P.PROJECT_ID
             , P.PROJECT_NAME
             , P.CUSTOMER_NAME
             , P.STATUS_CODE
             , P.ORDER_AMOUNT_VAT
             , P.CONTRACT_AMOUNT_VAT
             , P.PROJECT_START_DATE
             , P.PROJECT_END_DATE
          FROM "INIT$_TB_PROJECT" P
         WHERE 1=1
           AND P.PROJECT_YEAR = :planYear
           AND P.STATUS_CODE IN ('PLANNED', 'BIDDING')
         ORDER BY CASE P.STATUS_CODE WHEN 'BIDDING' THEN 1 ELSE 2 END
                , P.PROJECT_START_DATE NULLS LAST
                , P.PROJECT_ID DESC
       )
 WHERE ROWNUM <= 8
;

-- [HOME_NOTICE_FILES]
SELECT FILE_ID
     , NOTICE_ID
     , FILE_NAME
     , CONTENT_TYPE
     , FILE_SIZE
     , SORT_ORDER
  FROM "INIT$_TB_NOTICE_FILE"
 WHERE NOTICE_ID = :noticeId
   AND USE_YN = 'Y'
 ORDER BY SORT_ORDER
        , FILE_ID
;

-- [HOME_NOTICE_FILE_DOWNLOAD]
SELECT F.FILE_ID
     , F.NOTICE_ID
     , F.FILE_NAME
     , F.CONTENT_TYPE
     , F.FILE_SIZE
     , F.FILE_DATA
  FROM "INIT$_TB_NOTICE_FILE" F
  JOIN "INIT$_TB_NOTICE" N
    ON N.NOTICE_ID = F.NOTICE_ID
 WHERE F.FILE_ID = :fileId
   AND F.USE_YN = 'Y'
   AND N.USE_YN = 'Y'
   AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
   AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP)
;
