/*
 * INIT 시스템 DB 증분 반영 스크립트
 *
 * - 기존 테이블을 DROP하거나 데이터를 삭제하지 않습니다.
 * - 여러 번 실행해도 이미 존재하는 테이블, 컬럼, 제약조건은 건너뜁니다.
 * - 신규 컬럼은 INIT_SYSTEM_DDL.sql의 해당 테이블 맨 뒤에도 같은 순서로 추가합니다.
 * - Oracle은 기존 컬럼 사이에 새 컬럼을 물리적으로 삽입할 수 없으므로,
 *   DROP 없이 컬럼 순서를 유지하려면 신규 컬럼을 두 파일 모두 맨 뒤에 추가해야 합니다.
 */
SET SERVEROUTPUT ON

DECLARE
    FUNCTION OBJECT_EXISTS(
        P_OBJECT_NAME IN VARCHAR2
      , P_OBJECT_TYPE IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_OBJECTS
         WHERE OBJECT_NAME = UPPER(P_OBJECT_NAME)
           AND OBJECT_TYPE = UPPER(P_OBJECT_TYPE);
        RETURN V_COUNT > 0;
    END;

    FUNCTION COLUMN_EXISTS(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = UPPER(P_TABLE_NAME)
           AND COLUMN_NAME = UPPER(P_COLUMN_NAME);
        RETURN V_COUNT > 0;
    END;

    FUNCTION COLUMN_IS_NULLABLE(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = UPPER(P_TABLE_NAME)
           AND COLUMN_NAME = UPPER(P_COLUMN_NAME)
           AND NULLABLE = 'Y';
        RETURN V_COUNT > 0;
    END;

    FUNCTION CONSTRAINT_EXISTS(
        P_CONSTRAINT_NAME IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_CONSTRAINTS
         WHERE CONSTRAINT_NAME = UPPER(P_CONSTRAINT_NAME);
        RETURN V_COUNT > 0;
    END;

    PROCEDURE RUN_DDL(
        P_DDL IN CLOB
      , P_LABEL IN VARCHAR2
    ) IS
    BEGIN
        EXECUTE IMMEDIATE P_DDL;
        DBMS_OUTPUT.PUT_LINE('[OK] ' || P_LABEL);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('[ERROR] ' || P_LABEL || ' - ' || SQLERRM);
            RAISE;
    END;

    PROCEDURE CREATE_TABLE_IF_MISSING(
        P_TABLE_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF OBJECT_EXISTS(P_TABLE_NAME, 'TABLE') THEN
            DBMS_OUTPUT.PUT_LINE('[SKIP] TABLE ' || P_TABLE_NAME || ' already exists');
        ELSE
            RUN_DDL(P_DDL, 'CREATE TABLE ' || P_TABLE_NAME);
        END IF;
    END;

    PROCEDURE ADD_COLUMN_IF_MISSING(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
      , P_COLUMN_DEFINITION IN VARCHAR2
    ) IS
        V_ROW_EXISTS NUMBER := 0;
        V_DEFINITION VARCHAR2(4000) := UPPER(P_COLUMN_DEFINITION);
    BEGIN
        IF COLUMN_EXISTS(P_TABLE_NAME, P_COLUMN_NAME) THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] COLUMN ' || P_TABLE_NAME || '.' || P_COLUMN_NAME || ' already exists'
            );
        ELSE
            IF V_DEFINITION LIKE '%NOT NULL%'
               AND (
                    V_DEFINITION NOT LIKE '% DEFAULT %'
                    OR V_DEFINITION LIKE '%IDENTITY%'
               ) THEN
                EXECUTE IMMEDIATE
                    'SELECT COUNT(*) FROM "' || UPPER(P_TABLE_NAME) || '" WHERE ROWNUM = 1'
                    INTO V_ROW_EXISTS;
                IF V_ROW_EXISTS > 0 THEN
                    RAISE_APPLICATION_ERROR(
                        -20002
                      , 'ALT 중단: 데이터가 있는 ' || UPPER(P_TABLE_NAME)
                     || ' 테이블에 필수 컬럼 ' || UPPER(P_COLUMN_NAME)
                     || '을 안전하게 보정할 수 없습니다. 백업 후 부분 스키마를 확인해 주세요.'
                    );
                END IF;
            END IF;
            RUN_DDL(
                'ALTER TABLE "' || UPPER(P_TABLE_NAME) || '" ADD ('
             || '"' || UPPER(P_COLUMN_NAME) || '" ' || P_COLUMN_DEFINITION || ')'
              , 'ADD COLUMN ' || P_TABLE_NAME || '.' || P_COLUMN_NAME
            );
        END IF;
    END;

    PROCEDURE MAKE_COLUMN_NULLABLE(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
    ) IS
    BEGIN
        IF COLUMN_IS_NULLABLE(P_TABLE_NAME, P_COLUMN_NAME) THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] COLUMN ' || P_TABLE_NAME || '.' || P_COLUMN_NAME
             || ' already allows NULL'
            );
        ELSE
            RUN_DDL(
                'ALTER TABLE "' || UPPER(P_TABLE_NAME) || '" MODIFY ('
             || '"' || UPPER(P_COLUMN_NAME) || '" NULL)'
              , 'MODIFY ' || P_TABLE_NAME || '.' || P_COLUMN_NAME || ' NULL'
            );
        END IF;
    END;

    PROCEDURE ADD_CONSTRAINT_IF_MISSING(
        P_CONSTRAINT_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF CONSTRAINT_EXISTS(P_CONSTRAINT_NAME) THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] CONSTRAINT ' || P_CONSTRAINT_NAME || ' already exists'
            );
        ELSE
            RUN_DDL(P_DDL, 'ADD CONSTRAINT ' || P_CONSTRAINT_NAME);
        END IF;
    END;

    PROCEDURE CREATE_UNIQUE_IF_DATA_VALID(
        P_INDEX_NAME IN VARCHAR2
      , P_DUPLICATE_GROUP_SQL IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
        V_DUPLICATE_GROUP_COUNT NUMBER := 0;
    BEGIN
        IF OBJECT_EXISTS(P_INDEX_NAME, 'INDEX') THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] INDEX ' || P_INDEX_NAME || ' already exists'
            );
            RETURN;
        END IF;

        EXECUTE IMMEDIATE P_DUPLICATE_GROUP_SQL INTO V_DUPLICATE_GROUP_COUNT;
        IF V_DUPLICATE_GROUP_COUNT > 0 THEN
            DBMS_OUTPUT.PUT_LINE(
                '[WARN] UNIQUE INDEX ' || P_INDEX_NAME
             || ' skipped because ' || V_DUPLICATE_GROUP_COUNT
             || ' duplicate group(s) exist; resolve duplicates and rerun INIT_SYSTEM_ALT.sql'
            );
        ELSE
            RUN_DDL(P_DDL, 'CREATE UNIQUE INDEX ' || P_INDEX_NAME);
        END IF;
    END;

    PROCEDURE CREATE_INDEX_IF_MISSING(
        P_INDEX_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF OBJECT_EXISTS(P_INDEX_NAME, 'INDEX') THEN
            DBMS_OUTPUT.PUT_LINE('[SKIP] INDEX ' || P_INDEX_NAME || ' already exists');
        ELSE
            RUN_DDL(P_DDL, 'CREATE INDEX ' || P_INDEX_NAME);
        END IF;
    END;
BEGIN
    /*
     * 2026-08 최초 비밀번호 변경 의무화
     *
     * 기존 사용자는 이미 정상 비밀번호를 사용 중인 것으로 보정하기 위해
     * 최초 ADD 시 Y를 채우고, 이후 신규 기본값은 N으로 변경합니다.
     */
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_USER'
      , 'PASSWORD_CHANGE_YN'
      , 'CHAR(1 BYTE) DEFAULT ''Y'' NOT NULL ENABLE'
    );
    RUN_DDL(
        'ALTER TABLE "INIT$_TB_USER" MODIFY ('
     || '"PASSWORD_CHANGE_YN" DEFAULT ''N'')'
      , 'MODIFY INIT$_TB_USER.PASSWORD_CHANGE_YN DEFAULT'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_PASSWORD_CHANGE'
      , 'ALTER TABLE "INIT$_TB_USER" '
     || 'ADD CONSTRAINT "INIT$_CK_USER_PASSWORD_CHANGE" '
     || 'CHECK ("PASSWORD_CHANGE_YN" IN (''Y'', ''N'')) ENABLE'
    );
    RUN_DDL(
        q'[COMMENT ON COLUMN "INIT$_TB_USER"."PASSWORD_CHANGE_YN" IS 'Initial password changed (Y/N)']'
      , 'COMMENT INIT$_TB_USER.PASSWORD_CHANGE_YN'
    );

    /*
     * 2026-08 임직원 인사 프로필
     *
     * 주민등록번호와 급여계좌 같은 고위험 정보는 저장하지 않고,
     * 포털 운영에 필요한 기본 인사정보와 프로필 사진만 관리합니다.
     */
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'EMPLOYEE_NO', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'GENDER_CODE', 'VARCHAR2(20 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'BIRTH_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_USER'
      , 'BIRTH_CALENDAR_CODE'
      , 'VARCHAR2(20 BYTE) DEFAULT ''SOLAR'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'HIRE_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'RETIREMENT_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_USER'
      , 'EMPLOYMENT_STATUS_CODE'
      , 'VARCHAR2(30 BYTE) DEFAULT ''ACTIVE'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'EMPLOYMENT_TYPE_CODE', 'VARCHAR2(30 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'DEPARTMENT_NAME', 'VARCHAR2(200 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'POSITION_NAME', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'JOB_TITLE', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'WORK_LOCATION', 'VARCHAR2(200 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'MOBILE_PHONE', 'VARCHAR2(50 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'OFFICE_PHONE', 'VARCHAR2(50 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'HR_NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'PHOTO_FILE_NAME', 'VARCHAR2(500 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'PHOTO_CONTENT_TYPE', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'PHOTO_FILE_SIZE', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'PHOTO_DATA', 'BLOB');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'PHOTO_UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'TECHNICAL_GRADE_CODE', 'VARCHAR2(30 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_USER', 'CAREER_MONTHS', 'NUMBER(5)');

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_UK_USER_EMPLOYEE_NO'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_UK_USER_EMPLOYEE_NO" '
     || 'UNIQUE ("EMPLOYEE_NO")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_GENDER'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_GENDER" '
     || 'CHECK ("GENDER_CODE" IS NULL OR '
     || '"GENDER_CODE" IN (''MALE'', ''FEMALE'', ''OTHER'', ''UNDISCLOSED'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_BIRTH_CALENDAR'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_BIRTH_CALENDAR" '
     || 'CHECK ("BIRTH_CALENDAR_CODE" IN (''SOLAR'', ''LUNAR'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_EMPLOYMENT_STATUS'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_EMPLOYMENT_STATUS" '
     || 'CHECK ("EMPLOYMENT_STATUS_CODE" IN (''ACTIVE'', ''LEAVE'', ''RETIRED'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_EMPLOYMENT_TYPE'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_EMPLOYMENT_TYPE" '
     || 'CHECK ("EMPLOYMENT_TYPE_CODE" IS NULL OR "EMPLOYMENT_TYPE_CODE" IN '
     || '(''REGULAR'', ''CONTRACT'', ''EXECUTIVE'', ''INTERN'', ''DISPATCH'', ''OTHER'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_EMPLOYMENT_DATES'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_EMPLOYMENT_DATES" '
     || 'CHECK ("RETIREMENT_DATE" IS NULL OR "HIRE_DATE" IS NULL '
     || 'OR "RETIREMENT_DATE" >= "HIRE_DATE") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_TECH_GRADE'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_TECH_GRADE" '
     || 'CHECK ("TECHNICAL_GRADE_CODE" IS NULL OR "TECHNICAL_GRADE_CODE" IN '
     || '(''PROFESSIONAL_ENGINEER'', ''SPECIAL'', ''ADVANCED'', ''INTERMEDIATE'', ''BEGINNER'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_CAREER_MONTHS'
      , 'ALTER TABLE "INIT$_TB_USER" ADD CONSTRAINT "INIT$_CK_USER_CAREER_MONTHS" '
     || 'CHECK ("CAREER_MONTHS" IS NULL OR "CAREER_MONTHS" BETWEEN 0 AND 1200) ENABLE'
    );
    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_USER" IS 'Employee HR profiles, portal accounts, and administrator roles']'
      , 'COMMENT INIT$_TB_USER'
    );

    /*
     * 2026-08 포털 디자인 스킨 설정
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_SYSTEM_SETTING 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_SYSTEM_SETTING', q'[
CREATE TABLE "INIT$_TB_SYSTEM_SETTING" (
    "SETTING_KEY" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "SETTING_VALUE" VARCHAR2(4000 BYTE) NOT NULL ENABLE
  , "SETTING_DESCRIPTION" VARCHAR2(500 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_SYSTEM_SETTING" PRIMARY KEY ("SETTING_KEY")
  , CONSTRAINT "INIT$_FK_SYSTEM_SETTING_CREATED_USER" FOREIGN KEY ("CREATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_SYSTEM_SETTING_UPDATED_USER" FOREIGN KEY ("UPDATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_KEY'
      , 'VARCHAR2(100 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_VALUE'
      , 'VARCHAR2(4000 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_DESCRIPTION'
      , 'VARCHAR2(500 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'CREATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'UPDATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'UPDATED_AT'
      , 'TIMESTAMP (6)'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_SYSTEM_SETTING'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_PK_SYSTEM_SETTING" PRIMARY KEY ("SETTING_KEY")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_SYSTEM_SETTING_CREATED_USER'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_FK_SYSTEM_SETTING_CREATED_USER" FOREIGN KEY ("CREATED_BY") '
     || 'REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_SYSTEM_SETTING_UPDATED_USER'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_FK_SYSTEM_SETTING_UPDATED_USER" FOREIGN KEY ("UPDATED_BY") '
     || 'REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );

    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_SYSTEM_SETTING" IS 'Portal runtime settings']'
      , 'COMMENT INIT$_TB_SYSTEM_SETTING'
    );

    /*
     * 2026-08 연도별 프로젝트 관리
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_PROJECT 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_PROJECT', q'[
CREATE TABLE "INIT$_TB_PROJECT" (
    "PROJECT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PROJECT_YEAR" NUMBER(4) NOT NULL ENABLE
  , "PROJECT_NAME" VARCHAR2(300 CHAR) NOT NULL ENABLE
  , "CUSTOMER_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "PROJECT_START_DATE" DATE NOT NULL ENABLE
  , "PROJECT_END_DATE" DATE NOT NULL ENABLE
  , "ORDER_AMOUNT_VAT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "CONTRACT_AMOUNT_VAT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "PARTICIPATION_TYPE_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE
  , "PARTICIPATION_RATE" NUMBER(5, 2) DEFAULT 100 NOT NULL ENABLE
  , "ORDER_DATE" DATE
  , "BID_DATE" DATE
  , "STATUS_CODE" VARCHAR2(30 BYTE) DEFAULT 'PLANNED' NOT NULL ENABLE
  , "DESCRIPTION" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_PROJECT" PRIMARY KEY ("PROJECT_ID")
  , CONSTRAINT "INIT$_FK_PROJECT_CREATED_USER" FOREIGN KEY ("CREATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PROJECT_UPDATED_USER" FOREIGN KEY ("UPDATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_YEAR" CHECK ("PROJECT_YEAR" BETWEEN 1900 AND 2100) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PERIOD"
        CHECK ("PROJECT_START_DATE" <= "PROJECT_END_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_AMOUNTS"
        CHECK ("ORDER_AMOUNT_VAT" >= 0 AND "CONTRACT_AMOUNT_VAT" >= 0) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PART_TYPE"
        CHECK ("PARTICIPATION_TYPE_CODE" IN ('LEAD', 'CONSORTIUM', 'SUBCONTRACT')) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PART_RATE"
        CHECK ("PARTICIPATION_RATE" BETWEEN 0 AND 100) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_STATUS"
        CHECK ("STATUS_CODE" IN ('PLANNED', 'BIDDING', 'CONTRACTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')) ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_ID'
      , 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_YEAR'
      , 'NUMBER(4) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_NAME'
      , 'VARCHAR2(300 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CUSTOMER_NAME'
      , 'VARCHAR2(200 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_START_DATE'
      , 'DATE NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_END_DATE'
      , 'DATE NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'ORDER_AMOUNT_VAT'
      , 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CONTRACT_AMOUNT_VAT'
      , 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PARTICIPATION_TYPE_CODE'
      , 'VARCHAR2(30 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PARTICIPATION_RATE'
      , 'NUMBER(5, 2) DEFAULT 100 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'ORDER_DATE'
      , 'DATE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'BID_DATE'
      , 'DATE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'STATUS_CODE'
      , 'VARCHAR2(30 BYTE) DEFAULT ''PLANNED'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'DESCRIPTION'
      , 'VARCHAR2(2000 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CREATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'UPDATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'UPDATED_AT'
      , 'TIMESTAMP (6)'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_PROJECT'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_PK_PROJECT" '
     || 'PRIMARY KEY ("PROJECT_ID")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_PROJECT_CREATED_USER'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_FK_PROJECT_CREATED_USER" '
     || 'FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_PROJECT_UPDATED_USER'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_FK_PROJECT_UPDATED_USER" '
     || 'FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_YEAR'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_YEAR" '
     || 'CHECK ("PROJECT_YEAR" BETWEEN 1900 AND 2100) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PERIOD'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PERIOD" '
     || 'CHECK ("PROJECT_START_DATE" <= "PROJECT_END_DATE") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_AMOUNTS'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_AMOUNTS" '
     || 'CHECK ("ORDER_AMOUNT_VAT" >= 0 AND "CONTRACT_AMOUNT_VAT" >= 0) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PART_TYPE'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PART_TYPE" '
     || 'CHECK ("PARTICIPATION_TYPE_CODE" IN (''LEAD'', ''CONSORTIUM'', ''SUBCONTRACT'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PART_RATE'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PART_RATE" '
     || 'CHECK ("PARTICIPATION_RATE" BETWEEN 0 AND 100) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_STATUS'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_STATUS" '
     || 'CHECK ("STATUS_CODE" IN (''PLANNED'', ''BIDDING'', ''CONTRACTED'', '
     || '''IN_PROGRESS'', ''COMPLETED'', ''CANCELLED'')) ENABLE'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_PROJECT_YEAR_STATUS'
      , 'CREATE INDEX "INIT$_IX_PROJECT_YEAR_STATUS" '
     || 'ON "INIT$_TB_PROJECT" ("PROJECT_YEAR", "STATUS_CODE", "PROJECT_ID")'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_PROJECT_PERIOD'
      , 'CREATE INDEX "INIT$_IX_PROJECT_PERIOD" '
     || 'ON "INIT$_TB_PROJECT" ("PROJECT_START_DATE", "PROJECT_END_DATE")'
    );
    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_PROJECT" IS 'Annual IT project management']'
      , 'COMMENT INIT$_TB_PROJECT'
    );

    /* 2026-08 회사, 협력업체 임직원, 본사 이력 관리 */
    CREATE_TABLE_IF_MISSING('INIT$_TB_COMPANY', q'[
CREATE TABLE "INIT$_TB_COMPANY" (
    "COMPANY_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "COMPANY_TYPE_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE
  , "COMPANY_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "BUSINESS_NUMBER" VARCHAR2(30 CHAR)
  , "REPRESENTATIVE_NAME" VARCHAR2(100 CHAR)
  , "BUSINESS_TYPE" VARCHAR2(200 CHAR)
  , "BUSINESS_ITEM" VARCHAR2(300 CHAR)
  , "EMAIL" VARCHAR2(300 CHAR)
  , "PHONE" VARCHAR2(50 CHAR)
  , "ADDRESS" VARCHAR2(500 CHAR)
  , "WEBSITE_URL" VARCHAR2(500 CHAR)
  , "ESTABLISHED_DATE" DATE
  , "USE_YN" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE
  , "NOTE" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_COMPANY" PRIMARY KEY ("COMPANY_ID")
  , CONSTRAINT "INIT$_UK_COMPANY_NAME" UNIQUE ("COMPANY_NAME")
  , CONSTRAINT "INIT$_UK_COMPANY_BUSINESS_NO" UNIQUE ("BUSINESS_NUMBER")
  , CONSTRAINT "INIT$_FK_COMPANY_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_COMPANY_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_COMPANY_TYPE" CHECK ("COMPANY_TYPE_CODE" IN ('HEADQUARTERS', 'PARTNER', 'FREELANCER')) ENABLE
  , CONSTRAINT "INIT$_CK_COMPANY_USE" CHECK ("USE_YN" IN ('Y', 'N')) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'COMPANY_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'COMPANY_TYPE_CODE', 'VARCHAR2(30 BYTE) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'COMPANY_NAME', 'VARCHAR2(200 CHAR) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'BUSINESS_NUMBER', 'VARCHAR2(30 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'REPRESENTATIVE_NAME', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'BUSINESS_TYPE', 'VARCHAR2(200 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'BUSINESS_ITEM', 'VARCHAR2(300 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'EMAIL', 'VARCHAR2(300 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'PHONE', 'VARCHAR2(50 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'ADDRESS', 'VARCHAR2(500 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'WEBSITE_URL', 'VARCHAR2(500 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'ESTABLISHED_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'USE_YN', 'CHAR(1 BYTE) DEFAULT ''Y'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY', 'UPDATED_AT', 'TIMESTAMP (6)');

    /* 자식 테이블의 FK 생성 전에 부분 스키마의 부모 PK를 먼저 복구합니다. */
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_COMPANY', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_PK_COMPANY" PRIMARY KEY ("COMPANY_ID")');

    CREATE_TABLE_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', q'[
CREATE TABLE "INIT$_TB_COMPANY_EMPLOYEE" (
    "COMPANY_EMPLOYEE_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "COMPANY_ID" NUMBER NOT NULL ENABLE
  , "EMPLOYEE_NO" VARCHAR2(100 CHAR)
  , "EMPLOYEE_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "DEPARTMENT_NAME" VARCHAR2(200 CHAR)
  , "POSITION_NAME" VARCHAR2(100 CHAR)
  , "JOB_TITLE" VARCHAR2(100 CHAR)
  , "EMAIL" VARCHAR2(300 CHAR)
  , "MOBILE_PHONE" VARCHAR2(50 CHAR)
  , "JOIN_DATE" DATE
  , "LEAVE_DATE" DATE
  , "USE_YN" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE
  , "NOTE" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , "GENDER_CODE" VARCHAR2(20 BYTE)
  , "AGE_YEARS" NUMBER(3)
  , "TECHNICAL_GRADE_CODE" VARCHAR2(30 BYTE)
  , "CAREER_MONTHS" NUMBER(5)
  , CONSTRAINT "INIT$_PK_COMPANY_EMPLOYEE" PRIMARY KEY ("COMPANY_EMPLOYEE_ID")
  , CONSTRAINT "INIT$_FK_COMPANY_EMP_COMPANY" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ENABLE
  , CONSTRAINT "INIT$_FK_COMPANY_EMP_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_COMPANY_EMP_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_UK_COMPANY_EMP_NO" UNIQUE ("COMPANY_ID", "EMPLOYEE_NO")
  , CONSTRAINT "INIT$_CK_COMPANY_EMP_USE" CHECK ("USE_YN" IN ('Y', 'N')) ENABLE
  , CONSTRAINT "INIT$_CK_COMPANY_EMP_DATES" CHECK ("LEAVE_DATE" IS NULL OR "JOIN_DATE" IS NULL OR "LEAVE_DATE" >= "JOIN_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_COMP_EMP_GENDER" CHECK ("GENDER_CODE" IS NULL OR "GENDER_CODE" IN ('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED')) ENABLE
  , CONSTRAINT "INIT$_CK_COMP_EMP_AGE" CHECK ("AGE_YEARS" IS NULL OR "AGE_YEARS" BETWEEN 0 AND 150) ENABLE
  , CONSTRAINT "INIT$_CK_COMP_EMP_TECH_GRADE" CHECK ("TECHNICAL_GRADE_CODE" IS NULL OR "TECHNICAL_GRADE_CODE" IN ('PROFESSIONAL_ENGINEER', 'SPECIAL', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER')) ENABLE
  , CONSTRAINT "INIT$_CK_COMP_EMP_CAREER" CHECK ("CAREER_MONTHS" IS NULL OR "CAREER_MONTHS" BETWEEN 0 AND 1200) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'COMPANY_EMPLOYEE_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'COMPANY_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'EMPLOYEE_NO', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'EMPLOYEE_NAME', 'VARCHAR2(200 CHAR) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'DEPARTMENT_NAME', 'VARCHAR2(200 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'POSITION_NAME', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'JOB_TITLE', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'EMAIL', 'VARCHAR2(300 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'MOBILE_PHONE', 'VARCHAR2(50 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'JOIN_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'LEAVE_DATE', 'DATE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'USE_YN', 'CHAR(1 BYTE) DEFAULT ''Y'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'GENDER_CODE', 'VARCHAR2(20 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'AGE_YEARS', 'NUMBER(3)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'TECHNICAL_GRADE_CODE', 'VARCHAR2(30 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_EMPLOYEE', 'CAREER_MONTHS', 'NUMBER(5)');

    CREATE_TABLE_IF_MISSING('INIT$_TB_COMPANY_HISTORY', q'[
CREATE TABLE "INIT$_TB_COMPANY_HISTORY" (
    "COMPANY_HISTORY_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "COMPANY_ID" NUMBER NOT NULL ENABLE
  , "HISTORY_DATE" DATE NOT NULL ENABLE
  , "HISTORY_TYPE_CODE" VARCHAR2(30 BYTE) DEFAULT 'OTHER' NOT NULL ENABLE
  , "TITLE" VARCHAR2(300 CHAR) NOT NULL ENABLE
  , "CONTENT" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_COMPANY_HISTORY" PRIMARY KEY ("COMPANY_HISTORY_ID")
  , CONSTRAINT "INIT$_FK_COMPANY_HIST_COMPANY" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_FK_COMPANY_HIST_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_COMPANY_HIST_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_COMPANY_HIST_TYPE" CHECK ("HISTORY_TYPE_CODE" IN ('ESTABLISHED', 'NAME_CHANGE', 'ADDRESS_CHANGE', 'CERTIFICATION', 'OTHER')) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'COMPANY_HISTORY_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'COMPANY_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'HISTORY_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'HISTORY_TYPE_CODE', 'VARCHAR2(30 BYTE) DEFAULT ''OTHER'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'TITLE', 'VARCHAR2(300 CHAR) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'CONTENT', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_COMPANY_HISTORY', 'UPDATED_AT', 'TIMESTAMP (6)');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_COMPANY', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_PK_COMPANY" PRIMARY KEY ("COMPANY_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_COMPANY_NAME', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_UK_COMPANY_NAME" UNIQUE ("COMPANY_NAME")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_COMPANY_BUSINESS_NO', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_UK_COMPANY_BUSINESS_NO" UNIQUE ("BUSINESS_NUMBER")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_CREATED', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_FK_COMPANY_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_UPDATED', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_FK_COMPANY_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMPANY_TYPE', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_CK_COMPANY_TYPE" CHECK ("COMPANY_TYPE_CODE" IN (''HEADQUARTERS'', ''PARTNER'', ''FREELANCER'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMPANY_USE', 'ALTER TABLE "INIT$_TB_COMPANY" ADD CONSTRAINT "INIT$_CK_COMPANY_USE" CHECK ("USE_YN" IN (''Y'', ''N'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_COMPANY_EMPLOYEE', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_PK_COMPANY_EMPLOYEE" PRIMARY KEY ("COMPANY_EMPLOYEE_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_EMP_COMPANY', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_FK_COMPANY_EMP_COMPANY" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_EMP_CREATED', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_FK_COMPANY_EMP_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_EMP_UPDATED', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_FK_COMPANY_EMP_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_COMPANY_EMP_NO', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_UK_COMPANY_EMP_NO" UNIQUE ("COMPANY_ID", "EMPLOYEE_NO")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMPANY_EMP_USE', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMPANY_EMP_USE" CHECK ("USE_YN" IN (''Y'', ''N'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMPANY_EMP_DATES', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMPANY_EMP_DATES" CHECK ("LEAVE_DATE" IS NULL OR "JOIN_DATE" IS NULL OR "LEAVE_DATE" >= "JOIN_DATE") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMP_EMP_GENDER', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMP_EMP_GENDER" CHECK ("GENDER_CODE" IS NULL OR "GENDER_CODE" IN (''MALE'', ''FEMALE'', ''OTHER'', ''UNDISCLOSED'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMP_EMP_AGE', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMP_EMP_AGE" CHECK ("AGE_YEARS" IS NULL OR "AGE_YEARS" BETWEEN 0 AND 150) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMP_EMP_TECH_GRADE', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMP_EMP_TECH_GRADE" CHECK ("TECHNICAL_GRADE_CODE" IS NULL OR "TECHNICAL_GRADE_CODE" IN (''PROFESSIONAL_ENGINEER'', ''SPECIAL'', ''ADVANCED'', ''INTERMEDIATE'', ''BEGINNER'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMP_EMP_CAREER', 'ALTER TABLE "INIT$_TB_COMPANY_EMPLOYEE" ADD CONSTRAINT "INIT$_CK_COMP_EMP_CAREER" CHECK ("CAREER_MONTHS" IS NULL OR "CAREER_MONTHS" BETWEEN 0 AND 1200) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_COMPANY_HISTORY', 'ALTER TABLE "INIT$_TB_COMPANY_HISTORY" ADD CONSTRAINT "INIT$_PK_COMPANY_HISTORY" PRIMARY KEY ("COMPANY_HISTORY_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_HIST_COMPANY', 'ALTER TABLE "INIT$_TB_COMPANY_HISTORY" ADD CONSTRAINT "INIT$_FK_COMPANY_HIST_COMPANY" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_HIST_CREATED', 'ALTER TABLE "INIT$_TB_COMPANY_HISTORY" ADD CONSTRAINT "INIT$_FK_COMPANY_HIST_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_COMPANY_HIST_UPDATED', 'ALTER TABLE "INIT$_TB_COMPANY_HISTORY" ADD CONSTRAINT "INIT$_FK_COMPANY_HIST_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_COMPANY_HIST_TYPE', 'ALTER TABLE "INIT$_TB_COMPANY_HISTORY" ADD CONSTRAINT "INIT$_CK_COMPANY_HIST_TYPE" CHECK ("HISTORY_TYPE_CODE" IN (''ESTABLISHED'', ''NAME_CHANGE'', ''ADDRESS_CHANGE'', ''CERTIFICATION'', ''OTHER'')) ENABLE');
    CREATE_INDEX_IF_MISSING('INIT$_IX_COMPANY_TYPE_USE', 'CREATE INDEX "INIT$_IX_COMPANY_TYPE_USE" ON "INIT$_TB_COMPANY" ("COMPANY_TYPE_CODE", "USE_YN", "COMPANY_NAME")');
    CREATE_INDEX_IF_MISSING('INIT$_UX_COMPANY_HEADQUARTERS', 'CREATE UNIQUE INDEX "INIT$_UX_COMPANY_HEADQUARTERS" ON "INIT$_TB_COMPANY" (CASE WHEN "COMPANY_TYPE_CODE" = ''HEADQUARTERS'' THEN "COMPANY_TYPE_CODE" END)');
    CREATE_INDEX_IF_MISSING('INIT$_UX_COMPANY_FREELANCER', 'CREATE UNIQUE INDEX "INIT$_UX_COMPANY_FREELANCER" ON "INIT$_TB_COMPANY" (CASE WHEN "COMPANY_TYPE_CODE" = ''FREELANCER'' THEN "COMPANY_TYPE_CODE" END)');
    CREATE_INDEX_IF_MISSING('INIT$_IX_COMPANY_EMPLOYEE_01', 'CREATE INDEX "INIT$_IX_COMPANY_EMPLOYEE_01" ON "INIT$_TB_COMPANY_EMPLOYEE" ("COMPANY_ID", "USE_YN", "EMPLOYEE_NAME")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_COMPANY_HISTORY_01', 'CREATE INDEX "INIT$_IX_COMPANY_HISTORY_01" ON "INIT$_TB_COMPANY_HISTORY" ("COMPANY_ID", "HISTORY_DATE", "COMPANY_HISTORY_ID")');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_COMPANY" IS 'Headquarters, partner company, and freelancer affiliation master']', 'COMMENT INIT$_TB_COMPANY');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_COMPANY_EMPLOYEE" IS 'Partner company employees and freelancers']', 'COMMENT INIT$_TB_COMPANY_EMPLOYEE');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_COMPANY_HISTORY" IS 'Headquarters company history']', 'COMMENT INIT$_TB_COMPANY_HISTORY');

    /* 2026-08 프로젝트 참여회사 및 투입인력 관리 */
    CREATE_TABLE_IF_MISSING('INIT$_TB_PROJECT_COMPANY', q'[
CREATE TABLE "INIT$_TB_PROJECT_COMPANY" (
    "PROJECT_COMPANY_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PROJECT_ID" NUMBER NOT NULL ENABLE
  , "COMPANY_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "PARTICIPATION_TYPE_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE
  , "SHARE_RATE" NUMBER(5, 2) DEFAULT 0 NOT NULL ENABLE
  , "NOTE" VARCHAR2(1000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , "COMPANY_ID" NUMBER
  , CONSTRAINT "INIT$_PK_PROJECT_COMPANY" PRIMARY KEY ("PROJECT_COMPANY_ID")
  , CONSTRAINT "INIT$_FK_PRJ_COMPANY_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_COMPANY_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_COMPANY_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_COMPANY_MASTER" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ENABLE
  , CONSTRAINT "INIT$_UK_PROJECT_COMPANY" UNIQUE ("PROJECT_ID", "COMPANY_NAME")
  , CONSTRAINT "INIT$_CK_PRJ_COMPANY_TYPE" CHECK ("PARTICIPATION_TYPE_CODE" IN ('LEAD', 'CONSORTIUM', 'SUBCONTRACT')) ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_COMPANY_SHARE" CHECK ("SHARE_RATE" BETWEEN 0 AND 100) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'PROJECT_COMPANY_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'PROJECT_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'COMPANY_NAME', 'VARCHAR2(200 CHAR) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'PARTICIPATION_TYPE_CODE', 'VARCHAR2(30 BYTE) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'SHARE_RATE', 'NUMBER(5, 2) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'NOTE', 'VARCHAR2(1000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_COMPANY', 'COMPANY_ID', 'NUMBER');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PROJECT_COMPANY', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_PK_PROJECT_COMPANY" PRIMARY KEY ("PROJECT_COMPANY_ID")');

    CREATE_TABLE_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', q'[
CREATE TABLE "INIT$_TB_PROJECT_ASSIGNMENT" (
    "ASSIGNMENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PROJECT_ID" NUMBER NOT NULL ENABLE
  , "USER_ID" NUMBER
  , "PROJECT_COMPANY_ID" NUMBER
  , "ASSIGNMENT_START_DATE" DATE NOT NULL ENABLE
  , "ASSIGNMENT_END_DATE" DATE NOT NULL ENABLE
  , "ALLOCATION_TYPE_CODE" VARCHAR2(30 BYTE) DEFAULT 'MONTHLY' NOT NULL ENABLE
  , "DEFAULT_MM" NUMBER(6, 2) DEFAULT 1 NOT NULL ENABLE
  , "WEEKLY_DAY_CODES" VARCHAR2(50 BYTE)
  , "MONTHLY_ALLOCATION_JSON" CLOB
  , "TOTAL_MM" NUMBER(10, 2) DEFAULT 0 NOT NULL ENABLE
  , "COST_UNIT_PRICE" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "SALES_UNIT_PRICE" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "TOTAL_COST_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "TOTAL_SALES_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "OPERATING_PROFIT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "NOTE" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , "COMPANY_EMPLOYEE_ID" NUMBER
  , "PROJECT_ROLE_NAME" VARCHAR2(100 CHAR)
  , "PRIMARY_DUTY" VARCHAR2(1000 CHAR)
  , "DISPLAY_ORDER" NUMBER(10) DEFAULT 0 NOT NULL ENABLE
  , "ASSIGNMENT_STATUS_CODE" VARCHAR2(20 BYTE) DEFAULT 'CONFIRMED' NOT NULL ENABLE
  , CONSTRAINT "INIT$_PK_PROJECT_ASSIGN" PRIMARY KEY ("ASSIGNMENT_ID")
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_USER" FOREIGN KEY ("USER_ID") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_COMPANY" FOREIGN KEY ("PROJECT_COMPANY_ID") REFERENCES "INIT$_TB_PROJECT_COMPANY" ("PROJECT_COMPANY_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PRJ_ASSIGN_COMPANY_EMP" FOREIGN KEY ("COMPANY_EMPLOYEE_ID") REFERENCES "INIT$_TB_COMPANY_EMPLOYEE" ("COMPANY_EMPLOYEE_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_PERSON" CHECK (("USER_ID" IS NOT NULL AND "COMPANY_EMPLOYEE_ID" IS NULL) OR ("USER_ID" IS NULL AND "COMPANY_EMPLOYEE_ID" IS NOT NULL)) ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_PERIOD" CHECK ("ASSIGNMENT_START_DATE" <= "ASSIGNMENT_END_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_TYPE" CHECK ("ALLOCATION_TYPE_CODE" IN ('MONTHLY', 'WEEKLY')) ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_STATUS" CHECK ("ASSIGNMENT_STATUS_CODE" IN ('CONFIRMED', 'PLANNED')) ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_MM" CHECK ("DEFAULT_MM" BETWEEN 0 AND 1 AND "TOTAL_MM" >= 0) ENABLE
  , CONSTRAINT "INIT$_CK_PRJ_ASSIGN_AMOUNTS" CHECK ("COST_UNIT_PRICE" >= 0 AND "SALES_UNIT_PRICE" >= 0 AND "TOTAL_COST_AMOUNT" >= 0 AND "TOTAL_SALES_AMOUNT" >= 0) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'ASSIGNMENT_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'PROJECT_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'USER_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'PROJECT_COMPANY_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'ASSIGNMENT_START_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'ASSIGNMENT_END_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'ALLOCATION_TYPE_CODE', 'VARCHAR2(30 BYTE) DEFAULT ''MONTHLY'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'DEFAULT_MM', 'NUMBER(6, 2) DEFAULT 1 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'WEEKLY_DAY_CODES', 'VARCHAR2(50 BYTE)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'MONTHLY_ALLOCATION_JSON', 'CLOB');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'TOTAL_MM', 'NUMBER(10, 2) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'COST_UNIT_PRICE', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'SALES_UNIT_PRICE', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'TOTAL_COST_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'TOTAL_SALES_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'OPERATING_PROFIT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'COMPANY_EMPLOYEE_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'PROJECT_ROLE_NAME', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'PRIMARY_DUTY', 'VARCHAR2(1000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'DISPLAY_ORDER', 'NUMBER(10) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PROJECT_ASSIGNMENT', 'ASSIGNMENT_STATUS_CODE', 'VARCHAR2(20 BYTE) DEFAULT ''CONFIRMED'' NOT NULL ENABLE');
    MAKE_COLUMN_NULLABLE('INIT$_TB_PROJECT_ASSIGNMENT', 'USER_ID');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PROJECT_COMPANY', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_PK_PROJECT_COMPANY" PRIMARY KEY ("PROJECT_COMPANY_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_COMPANY_PROJECT', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_FK_PRJ_COMPANY_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_COMPANY_CREATED', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_FK_PRJ_COMPANY_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_COMPANY_UPDATED', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_FK_PRJ_COMPANY_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_COMPANY_MASTER', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_FK_PRJ_COMPANY_MASTER" FOREIGN KEY ("COMPANY_ID") REFERENCES "INIT$_TB_COMPANY" ("COMPANY_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_PROJECT_COMPANY', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_UK_PROJECT_COMPANY" UNIQUE ("PROJECT_ID", "COMPANY_NAME")');
    CREATE_UNIQUE_IF_DATA_VALID(
        'INIT$_UX_PRJ_COMPANY_MASTER'
      , q'[
SELECT COUNT(*)
  FROM (
        SELECT "PROJECT_ID"
             , "COMPANY_ID"
          FROM "INIT$_TB_PROJECT_COMPANY"
         WHERE "COMPANY_ID" IS NOT NULL
         GROUP BY "PROJECT_ID"
                , "COMPANY_ID"
        HAVING COUNT(*) > 1
       )
]'
      , 'CREATE UNIQUE INDEX "INIT$_UX_PRJ_COMPANY_MASTER" ON "INIT$_TB_PROJECT_COMPANY" ('
     || 'CASE WHEN "COMPANY_ID" IS NOT NULL THEN "PROJECT_ID" END, '
     || 'CASE WHEN "COMPANY_ID" IS NOT NULL THEN "COMPANY_ID" END)'
    );
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_COMPANY_TYPE', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_CK_PRJ_COMPANY_TYPE" CHECK ("PARTICIPATION_TYPE_CODE" IN (''LEAD'', ''CONSORTIUM'', ''SUBCONTRACT'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_COMPANY_SHARE', 'ALTER TABLE "INIT$_TB_PROJECT_COMPANY" ADD CONSTRAINT "INIT$_CK_PRJ_COMPANY_SHARE" CHECK ("SHARE_RATE" BETWEEN 0 AND 100) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PROJECT_ASSIGN', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_PK_PROJECT_ASSIGN" PRIMARY KEY ("ASSIGNMENT_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_PROJECT', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_USER', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_USER" FOREIGN KEY ("USER_ID") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_COMPANY', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_COMPANY" FOREIGN KEY ("PROJECT_COMPANY_ID") REFERENCES "INIT$_TB_PROJECT_COMPANY" ("PROJECT_COMPANY_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_CREATED', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_UPDATED', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PRJ_ASSIGN_COMPANY_EMP', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PRJ_ASSIGN_COMPANY_EMP" FOREIGN KEY ("COMPANY_EMPLOYEE_ID") REFERENCES "INIT$_TB_COMPANY_EMPLOYEE" ("COMPANY_EMPLOYEE_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_PERSON', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_PERSON" CHECK (("USER_ID" IS NOT NULL AND "COMPANY_EMPLOYEE_ID" IS NULL) OR ("USER_ID" IS NULL AND "COMPANY_EMPLOYEE_ID" IS NOT NULL)) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_PERIOD', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_PERIOD" CHECK ("ASSIGNMENT_START_DATE" <= "ASSIGNMENT_END_DATE") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_TYPE', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_TYPE" CHECK ("ALLOCATION_TYPE_CODE" IN (''MONTHLY'', ''WEEKLY'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_STATUS', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_STATUS" CHECK ("ASSIGNMENT_STATUS_CODE" IN (''CONFIRMED'', ''PLANNED'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_MM', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_MM" CHECK ("DEFAULT_MM" BETWEEN 0 AND 1 AND "TOTAL_MM" >= 0) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PRJ_ASSIGN_AMOUNTS', 'ALTER TABLE "INIT$_TB_PROJECT_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PRJ_ASSIGN_AMOUNTS" CHECK ("COST_UNIT_PRICE" >= 0 AND "SALES_UNIT_PRICE" >= 0 AND "TOTAL_COST_AMOUNT" >= 0 AND "TOTAL_SALES_AMOUNT" >= 0) ENABLE');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PRJ_COMPANY_PROJECT', 'CREATE INDEX "INIT$_IX_PRJ_COMPANY_PROJECT" ON "INIT$_TB_PROJECT_COMPANY" ("PROJECT_ID", "PROJECT_COMPANY_ID")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PRJ_ASSIGN_PROJECT', 'CREATE INDEX "INIT$_IX_PRJ_ASSIGN_PROJECT" ON "INIT$_TB_PROJECT_ASSIGNMENT" ("PROJECT_ID", "ASSIGNMENT_START_DATE", "ASSIGNMENT_ID")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PRJ_ASSIGN_USER', 'CREATE INDEX "INIT$_IX_PRJ_ASSIGN_USER" ON "INIT$_TB_PROJECT_ASSIGNMENT" ("USER_ID", "ASSIGNMENT_START_DATE", "ASSIGNMENT_END_DATE")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PRJ_ASSIGN_COMPANY_EMP', 'CREATE INDEX "INIT$_IX_PRJ_ASSIGN_COMPANY_EMP" ON "INIT$_TB_PROJECT_ASSIGNMENT" ("COMPANY_EMPLOYEE_ID", "ASSIGNMENT_START_DATE", "ASSIGNMENT_END_DATE")');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PROJECT_COMPANY" IS 'Project participating companies and revenue share']', 'COMMENT INIT$_TB_PROJECT_COMPANY');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PROJECT_ASSIGNMENT" IS 'Employee project staffing, M/M allocation, and profitability']', 'COMMENT INIT$_TB_PROJECT_ASSIGNMENT');

    /*
     * 2026-08 연간 사업·인력계획 시나리오
     *
     * 확정·실제 투입 테이블과 계획 시뮬레이션을 분리하고 월별 M/M을
     * 조회 가능한 행 구조로 저장합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_PLAN_SCENARIO', q'[
CREATE TABLE "INIT$_TB_PLAN_SCENARIO" (
    "SCENARIO_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PLAN_YEAR" NUMBER(4) NOT NULL ENABLE
  , "SCENARIO_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "STATUS_CODE" VARCHAR2(30 BYTE) DEFAULT 'DRAFT' NOT NULL ENABLE
  , "REVISION_NO" NUMBER DEFAULT 1 NOT NULL ENABLE
  , "DESCRIPTION" VARCHAR2(2000 CHAR)
  , "BASE_SCENARIO_ID" NUMBER
  , "CONFIRMED_BY" NUMBER
  , "CONFIRMED_AT" TIMESTAMP (6)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_PLAN_SCENARIO" PRIMARY KEY ("SCENARIO_ID")
  , CONSTRAINT "INIT$_UK_PLAN_SCENARIO_NAME" UNIQUE ("PLAN_YEAR", "SCENARIO_NAME")
  , CONSTRAINT "INIT$_FK_PLAN_SCN_BASE" FOREIGN KEY ("BASE_SCENARIO_ID") REFERENCES "INIT$_TB_PLAN_SCENARIO" ("SCENARIO_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_SCN_CONFIRMED" FOREIGN KEY ("CONFIRMED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_SCN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_SCN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_SCN_YEAR" CHECK ("PLAN_YEAR" BETWEEN 1900 AND 2100) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_SCN_STATUS" CHECK ("STATUS_CODE" IN ('DRAFT', 'CONFIRMED', 'ARCHIVED')) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_SCN_REV" CHECK ("REVISION_NO" >= 1) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'SCENARIO_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'PLAN_YEAR', 'NUMBER(4) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'SCENARIO_NAME', 'VARCHAR2(200 CHAR) NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'STATUS_CODE', 'VARCHAR2(30 BYTE) DEFAULT ''DRAFT'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'REVISION_NO', 'NUMBER DEFAULT 1 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'DESCRIPTION', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'BASE_SCENARIO_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'CONFIRMED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'CONFIRMED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_SCENARIO', 'UPDATED_AT', 'TIMESTAMP (6)');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_SCENARIO', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_PK_PLAN_SCENARIO" PRIMARY KEY ("SCENARIO_ID")');

    CREATE_TABLE_IF_MISSING('INIT$_TB_PLAN_PROJECT', q'[
CREATE TABLE "INIT$_TB_PLAN_PROJECT" (
    "SCENARIO_PROJECT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "SCENARIO_ID" NUMBER NOT NULL ENABLE
  , "PROJECT_ID" NUMBER NOT NULL ENABLE
  , "BID_DECISION_CODE" VARCHAR2(30 BYTE) DEFAULT 'REVIEW' NOT NULL ENABLE
  , "WIN_PROBABILITY" NUMBER(5, 2) DEFAULT 0 NOT NULL ENABLE
  , "PLANNED_START_DATE" DATE NOT NULL ENABLE
  , "PLANNED_END_DATE" DATE NOT NULL ENABLE
  , "ANNOUNCEMENT_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "BID_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "EXPECTED_CONTRACT_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "DISCOUNT_RATE" NUMBER(9, 4) DEFAULT 0 NOT NULL ENABLE
  , "SORT_ORDER" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "NOTE" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , "TARGET_HEADCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE
  , CONSTRAINT "INIT$_PK_PLAN_PROJECT" PRIMARY KEY ("SCENARIO_PROJECT_ID")
  , CONSTRAINT "INIT$_UK_PLAN_PROJECT" UNIQUE ("SCENARIO_ID", "PROJECT_ID")
  , CONSTRAINT "INIT$_FK_PLAN_PRJ_SCENARIO" FOREIGN KEY ("SCENARIO_ID") REFERENCES "INIT$_TB_PLAN_SCENARIO" ("SCENARIO_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_PRJ_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_PRJ_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_PRJ_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_PRJ_BID" CHECK ("BID_DECISION_CODE" IN ('REVIEW', 'PARTICIPATE', 'HOLD', 'SKIP')) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_PRJ_PROB" CHECK ("WIN_PROBABILITY" BETWEEN 0 AND 100) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_PRJ_PERIOD" CHECK ("PLANNED_START_DATE" <= "PLANNED_END_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_PRJ_AMOUNT" CHECK ("ANNOUNCEMENT_AMOUNT" >= 0 AND "BID_AMOUNT" >= 0 AND "EXPECTED_CONTRACT_AMOUNT" >= 0) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_PRJ_HEADCOUNT" CHECK ("TARGET_HEADCOUNT" >= 0) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'SCENARIO_PROJECT_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'SCENARIO_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'PROJECT_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'BID_DECISION_CODE', 'VARCHAR2(30 BYTE) DEFAULT ''REVIEW'' NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'WIN_PROBABILITY', 'NUMBER(5, 2) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'PLANNED_START_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'PLANNED_END_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'ANNOUNCEMENT_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'BID_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'EXPECTED_CONTRACT_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'DISCOUNT_RATE', 'NUMBER(9, 4) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'SORT_ORDER', 'NUMBER DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_PROJECT', 'TARGET_HEADCOUNT', 'NUMBER DEFAULT 0 NOT NULL ENABLE');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_PROJECT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_PK_PLAN_PROJECT" PRIMARY KEY ("SCENARIO_PROJECT_ID")');

    CREATE_TABLE_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', q'[
CREATE TABLE "INIT$_TB_PLAN_ASSIGNMENT" (
    "PLAN_ASSIGNMENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "SCENARIO_PROJECT_ID" NUMBER NOT NULL ENABLE
  , "USER_ID" NUMBER
  , "COMPANY_EMPLOYEE_ID" NUMBER
  , "ASSIGNMENT_START_DATE" DATE NOT NULL ENABLE
  , "ASSIGNMENT_END_DATE" DATE NOT NULL ENABLE
  , "TOTAL_MM" NUMBER(10, 2) DEFAULT 0 NOT NULL ENABLE
  , "COST_UNIT_PRICE" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "SALES_UNIT_PRICE" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "TOTAL_COST_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "TOTAL_SALES_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "OPERATING_PROFIT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "SORT_ORDER" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "NOTE" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , "PROJECT_ROLE_NAME" VARCHAR2(100 CHAR)
  , "PRIMARY_DUTY" VARCHAR2(1000 CHAR)
  , CONSTRAINT "INIT$_PK_PLAN_ASSIGN" PRIMARY KEY ("PLAN_ASSIGNMENT_ID")
  , CONSTRAINT "INIT$_FK_PLAN_ASN_PROJECT" FOREIGN KEY ("SCENARIO_PROJECT_ID") REFERENCES "INIT$_TB_PLAN_PROJECT" ("SCENARIO_PROJECT_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_ASN_USER" FOREIGN KEY ("USER_ID") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_ASN_COMP_EMP" FOREIGN KEY ("COMPANY_EMPLOYEE_ID") REFERENCES "INIT$_TB_COMPANY_EMPLOYEE" ("COMPANY_EMPLOYEE_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_ASN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PLAN_ASN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_ASN_PERSON" CHECK (("USER_ID" IS NOT NULL AND "COMPANY_EMPLOYEE_ID" IS NULL) OR ("USER_ID" IS NULL AND "COMPANY_EMPLOYEE_ID" IS NOT NULL)) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_ASN_PERIOD" CHECK ("ASSIGNMENT_START_DATE" <= "ASSIGNMENT_END_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_ASN_MM" CHECK ("TOTAL_MM" >= 0) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_ASN_AMOUNT" CHECK ("COST_UNIT_PRICE" >= 0 AND "SALES_UNIT_PRICE" >= 0 AND "TOTAL_COST_AMOUNT" >= 0 AND "TOTAL_SALES_AMOUNT" >= 0) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'PLAN_ASSIGNMENT_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'SCENARIO_PROJECT_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'USER_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'COMPANY_EMPLOYEE_ID', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'ASSIGNMENT_START_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'ASSIGNMENT_END_DATE', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'TOTAL_MM', 'NUMBER(10, 2) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'COST_UNIT_PRICE', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'SALES_UNIT_PRICE', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'TOTAL_COST_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'TOTAL_SALES_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'OPERATING_PROFIT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'SORT_ORDER', 'NUMBER DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'NOTE', 'VARCHAR2(2000 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'CREATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'CREATED_AT', 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'UPDATED_BY', 'NUMBER');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'UPDATED_AT', 'TIMESTAMP (6)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'PROJECT_ROLE_NAME', 'VARCHAR2(100 CHAR)');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_ASSIGNMENT', 'PRIMARY_DUTY', 'VARCHAR2(1000 CHAR)');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_ASSIGN', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_PK_PLAN_ASSIGN" PRIMARY KEY ("PLAN_ASSIGNMENT_ID")');

    CREATE_TABLE_IF_MISSING('INIT$_TB_PLAN_MONTH', q'[
CREATE TABLE "INIT$_TB_PLAN_MONTH" (
    "PLAN_MONTH_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PLAN_ASSIGNMENT_ID" NUMBER NOT NULL ENABLE
  , "ALLOCATION_MONTH" DATE NOT NULL ENABLE
  , "MM" NUMBER(6, 2) DEFAULT 0 NOT NULL ENABLE
  , "COST_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "SALES_AMOUNT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "OPERATING_PROFIT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , CONSTRAINT "INIT$_PK_PLAN_MONTH" PRIMARY KEY ("PLAN_MONTH_ID")
  , CONSTRAINT "INIT$_UK_PLAN_MONTH" UNIQUE ("PLAN_ASSIGNMENT_ID", "ALLOCATION_MONTH")
  , CONSTRAINT "INIT$_FK_PLAN_MONTH_ASSIGN" FOREIGN KEY ("PLAN_ASSIGNMENT_ID") REFERENCES "INIT$_TB_PLAN_ASSIGNMENT" ("PLAN_ASSIGNMENT_ID") ON DELETE CASCADE ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_MONTH_DATE" CHECK ("ALLOCATION_MONTH" = TRUNC("ALLOCATION_MONTH", 'MM')) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_MONTH_MM" CHECK ("MM" BETWEEN 0 AND 1) ENABLE
  , CONSTRAINT "INIT$_CK_PLAN_MONTH_AMOUNT" CHECK ("COST_AMOUNT" >= 0 AND "SALES_AMOUNT" >= 0) ENABLE
)
]');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'PLAN_MONTH_ID', 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'PLAN_ASSIGNMENT_ID', 'NUMBER NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'ALLOCATION_MONTH', 'DATE NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'MM', 'NUMBER(6, 2) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'COST_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'SALES_AMOUNT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');
    ADD_COLUMN_IF_MISSING('INIT$_TB_PLAN_MONTH', 'OPERATING_PROFIT', 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE');

    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_SCENARIO', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_PK_PLAN_SCENARIO" PRIMARY KEY ("SCENARIO_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_PLAN_SCENARIO_NAME', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_UK_PLAN_SCENARIO_NAME" UNIQUE ("PLAN_YEAR", "SCENARIO_NAME")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_SCN_BASE', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_FK_PLAN_SCN_BASE" FOREIGN KEY ("BASE_SCENARIO_ID") REFERENCES "INIT$_TB_PLAN_SCENARIO" ("SCENARIO_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_SCN_CONFIRMED', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_FK_PLAN_SCN_CONFIRMED" FOREIGN KEY ("CONFIRMED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_SCN_CREATED', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_FK_PLAN_SCN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_SCN_UPDATED', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_FK_PLAN_SCN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_SCN_YEAR', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_CK_PLAN_SCN_YEAR" CHECK ("PLAN_YEAR" BETWEEN 1900 AND 2100) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_SCN_STATUS', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_CK_PLAN_SCN_STATUS" CHECK ("STATUS_CODE" IN (''DRAFT'', ''CONFIRMED'', ''ARCHIVED'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_SCN_REV', 'ALTER TABLE "INIT$_TB_PLAN_SCENARIO" ADD CONSTRAINT "INIT$_CK_PLAN_SCN_REV" CHECK ("REVISION_NO" >= 1) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_PROJECT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_PK_PLAN_PROJECT" PRIMARY KEY ("SCENARIO_PROJECT_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_PLAN_PROJECT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_UK_PLAN_PROJECT" UNIQUE ("SCENARIO_ID", "PROJECT_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_PRJ_SCENARIO', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_FK_PLAN_PRJ_SCENARIO" FOREIGN KEY ("SCENARIO_ID") REFERENCES "INIT$_TB_PLAN_SCENARIO" ("SCENARIO_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_PRJ_PROJECT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_FK_PLAN_PRJ_PROJECT" FOREIGN KEY ("PROJECT_ID") REFERENCES "INIT$_TB_PROJECT" ("PROJECT_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_PRJ_CREATED', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_FK_PLAN_PRJ_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_PRJ_UPDATED', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_FK_PLAN_PRJ_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_PRJ_BID', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_CK_PLAN_PRJ_BID" CHECK ("BID_DECISION_CODE" IN (''REVIEW'', ''PARTICIPATE'', ''HOLD'', ''SKIP'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_PRJ_PROB', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_CK_PLAN_PRJ_PROB" CHECK ("WIN_PROBABILITY" BETWEEN 0 AND 100) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_PRJ_PERIOD', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_CK_PLAN_PRJ_PERIOD" CHECK ("PLANNED_START_DATE" <= "PLANNED_END_DATE") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_PRJ_AMOUNT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_CK_PLAN_PRJ_AMOUNT" CHECK ("ANNOUNCEMENT_AMOUNT" >= 0 AND "BID_AMOUNT" >= 0 AND "EXPECTED_CONTRACT_AMOUNT" >= 0) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_PRJ_HEADCOUNT', 'ALTER TABLE "INIT$_TB_PLAN_PROJECT" ADD CONSTRAINT "INIT$_CK_PLAN_PRJ_HEADCOUNT" CHECK ("TARGET_HEADCOUNT" >= 0) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_ASSIGN', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_PK_PLAN_ASSIGN" PRIMARY KEY ("PLAN_ASSIGNMENT_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_ASN_PROJECT', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PLAN_ASN_PROJECT" FOREIGN KEY ("SCENARIO_PROJECT_ID") REFERENCES "INIT$_TB_PLAN_PROJECT" ("SCENARIO_PROJECT_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_ASN_USER', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PLAN_ASN_USER" FOREIGN KEY ("USER_ID") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_ASN_COMP_EMP', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PLAN_ASN_COMP_EMP" FOREIGN KEY ("COMPANY_EMPLOYEE_ID") REFERENCES "INIT$_TB_COMPANY_EMPLOYEE" ("COMPANY_EMPLOYEE_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_ASN_CREATED', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PLAN_ASN_CREATED" FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_ASN_UPDATED', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_FK_PLAN_ASN_UPDATED" FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_ASN_PERSON', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PLAN_ASN_PERSON" CHECK (("USER_ID" IS NOT NULL AND "COMPANY_EMPLOYEE_ID" IS NULL) OR ("USER_ID" IS NULL AND "COMPANY_EMPLOYEE_ID" IS NOT NULL)) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_ASN_PERIOD', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PLAN_ASN_PERIOD" CHECK ("ASSIGNMENT_START_DATE" <= "ASSIGNMENT_END_DATE") ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_ASN_MM', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PLAN_ASN_MM" CHECK ("TOTAL_MM" >= 0) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_ASN_AMOUNT', 'ALTER TABLE "INIT$_TB_PLAN_ASSIGNMENT" ADD CONSTRAINT "INIT$_CK_PLAN_ASN_AMOUNT" CHECK ("COST_UNIT_PRICE" >= 0 AND "SALES_UNIT_PRICE" >= 0 AND "TOTAL_COST_AMOUNT" >= 0 AND "TOTAL_SALES_AMOUNT" >= 0) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_PK_PLAN_MONTH', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_PK_PLAN_MONTH" PRIMARY KEY ("PLAN_MONTH_ID")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_UK_PLAN_MONTH', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_UK_PLAN_MONTH" UNIQUE ("PLAN_ASSIGNMENT_ID", "ALLOCATION_MONTH")');
    ADD_CONSTRAINT_IF_MISSING('INIT$_FK_PLAN_MONTH_ASSIGN', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_FK_PLAN_MONTH_ASSIGN" FOREIGN KEY ("PLAN_ASSIGNMENT_ID") REFERENCES "INIT$_TB_PLAN_ASSIGNMENT" ("PLAN_ASSIGNMENT_ID") ON DELETE CASCADE ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_MONTH_DATE', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_CK_PLAN_MONTH_DATE" CHECK ("ALLOCATION_MONTH" = TRUNC("ALLOCATION_MONTH", ''MM'')) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_MONTH_MM', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_CK_PLAN_MONTH_MM" CHECK ("MM" BETWEEN 0 AND 1) ENABLE');
    ADD_CONSTRAINT_IF_MISSING('INIT$_CK_PLAN_MONTH_AMOUNT', 'ALTER TABLE "INIT$_TB_PLAN_MONTH" ADD CONSTRAINT "INIT$_CK_PLAN_MONTH_AMOUNT" CHECK ("COST_AMOUNT" >= 0 AND "SALES_AMOUNT" >= 0) ENABLE');

    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_SCN_YEAR_STATUS', 'CREATE INDEX "INIT$_IX_PLAN_SCN_YEAR_STATUS" ON "INIT$_TB_PLAN_SCENARIO" ("PLAN_YEAR", "STATUS_CODE", "SCENARIO_ID")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_PRJ_SCENARIO', 'CREATE INDEX "INIT$_IX_PLAN_PRJ_SCENARIO" ON "INIT$_TB_PLAN_PROJECT" ("SCENARIO_ID", "SORT_ORDER", "SCENARIO_PROJECT_ID")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_ASN_PROJECT', 'CREATE INDEX "INIT$_IX_PLAN_ASN_PROJECT" ON "INIT$_TB_PLAN_ASSIGNMENT" ("SCENARIO_PROJECT_ID", "SORT_ORDER", "PLAN_ASSIGNMENT_ID")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_ASN_USER', 'CREATE INDEX "INIT$_IX_PLAN_ASN_USER" ON "INIT$_TB_PLAN_ASSIGNMENT" ("USER_ID", "ASSIGNMENT_START_DATE", "ASSIGNMENT_END_DATE")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_ASN_COMP_EMP', 'CREATE INDEX "INIT$_IX_PLAN_ASN_COMP_EMP" ON "INIT$_TB_PLAN_ASSIGNMENT" ("COMPANY_EMPLOYEE_ID", "ASSIGNMENT_START_DATE", "ASSIGNMENT_END_DATE")');
    CREATE_INDEX_IF_MISSING('INIT$_IX_PLAN_MONTH_MONTH', 'CREATE INDEX "INIT$_IX_PLAN_MONTH_MONTH" ON "INIT$_TB_PLAN_MONTH" ("ALLOCATION_MONTH", "PLAN_ASSIGNMENT_ID")');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PLAN_SCENARIO" IS 'Annual business and workforce planning scenarios']', 'COMMENT INIT$_TB_PLAN_SCENARIO');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PLAN_PROJECT" IS 'Projects and bid assumptions included in a planning scenario']', 'COMMENT INIT$_TB_PLAN_PROJECT');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PLAN_ASSIGNMENT" IS 'Planned internal and external workforce assignments']', 'COMMENT INIT$_TB_PLAN_ASSIGNMENT');
    RUN_DDL(q'[COMMENT ON TABLE "INIT$_TB_PLAN_MONTH" IS 'Normalized monthly M/M and financial planning values']', 'COMMENT INIT$_TB_PLAN_MONTH');

    /*
     * 2026-07 AI 학습 트렌드 대시보드
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_AI_TRAINING_RUN 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_AI_TRAINING_RUN', q'[
CREATE TABLE "INIT$_TB_AI_TRAINING_RUN" (
    "TRAINING_RUN_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "MODEL_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "MODEL_VERSION" VARCHAR2(100 CHAR)
  , "STATUS_CODE" VARCHAR2(30 BYTE) DEFAULT 'PENDING' NOT NULL ENABLE
  , "DATASET_ROW_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "EPOCH_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "ACCURACY_SCORE" NUMBER(12, 8)
  , "LOSS_SCORE" NUMBER(12, 8)
  , "STARTED_AT" TIMESTAMP (6)
  , "COMPLETED_AT" TIMESTAMP (6)
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , CONSTRAINT "INIT$_PK_AI_TRAINING_RUN" PRIMARY KEY ("TRAINING_RUN_ID")
  , CONSTRAINT "INIT$_CK_AI_TRAINING_STATUS"
        CHECK ("STATUS_CODE" IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')) ENABLE
  , CONSTRAINT "INIT$_CK_AI_TRAINING_ACCURACY"
        CHECK ("ACCURACY_SCORE" IS NULL OR ("ACCURACY_SCORE" >= 0 AND "ACCURACY_SCORE" <= 1)) ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'TRAINING_RUN_ID'
      , 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'MODEL_NAME'
      , 'VARCHAR2(200 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'MODEL_VERSION'
      , 'VARCHAR2(100 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'STATUS_CODE'
      , 'VARCHAR2(30 BYTE) DEFAULT ''PENDING'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'DATASET_ROW_COUNT'
      , 'NUMBER DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'EPOCH_COUNT'
      , 'NUMBER DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'ACCURACY_SCORE'
      , 'NUMBER(12, 8)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'LOSS_SCORE'
      , 'NUMBER(12, 8)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'STARTED_AT'
      , 'TIMESTAMP (6)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'COMPLETED_AT'
      , 'TIMESTAMP (6)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_AI_TRAINING_RUN'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_PK_AI_TRAINING_RUN" PRIMARY KEY ("TRAINING_RUN_ID")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_AI_TRAINING_STATUS'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_CK_AI_TRAINING_STATUS" '
     || 'CHECK ("STATUS_CODE" IN (''PENDING'', ''RUNNING'', ''COMPLETED'', ''FAILED'', ''CANCELLED'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_AI_TRAINING_ACCURACY'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_CK_AI_TRAINING_ACCURACY" '
     || 'CHECK ("ACCURACY_SCORE" IS NULL '
     || 'OR ("ACCURACY_SCORE" >= 0 AND "ACCURACY_SCORE" <= 1)) ENABLE'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_AI_TRAINING_STATUS'
      , 'CREATE INDEX "INIT$_IX_AI_TRAINING_STATUS" '
     || 'ON "INIT$_TB_AI_TRAINING_RUN" ("STATUS_CODE", "COMPLETED_AT")'
    );
    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_AI_TRAINING_RUN" IS 'AI model training run metrics']'
      , 'COMMENT INIT$_TB_AI_TRAINING_RUN'
    );
END;
/
