/*
 * INIT Members 전체 데이터 초기화 스크립트
 *
 * 활성 FK가 있는 Oracle 테이블은 자식 데이터를 먼저 지워도 부모
 * TRUNCATE가 실패할 수 있습니다. 제약조건을 비활성화하는 DDL 대신
 * 정확한 allowlist를 자식부터 DELETE하여 스키마와 제약조건을 보존합니다.
 * 모든 삭제는 마지막 COMMIT 전까지 같은 트랜잭션에서 수행됩니다.
 * SQLcl/SQL*Plus 실행 예: @database/INIT_SYSTEM_TRUC.sql INIT_OWNER
 */
DEFINE INIT_EXPECTED_SCHEMA = '&1'

DECLARE
    V_EXTERNAL_FK_COUNT NUMBER := 0;
    V_REFERENCE_GRANT_COUNT NUMBER := 0;
    V_EXPECTED_SCHEMA VARCHAR2(128) := UPPER(TRIM('&&INIT_EXPECTED_SCHEMA'));
    V_SESSION_USER VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
    V_CURRENT_SCHEMA VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));

    PROCEDURE DELETE_IF_EXISTS(
        P_TABLE_NAME IN VARCHAR2
    ) IS
        V_TABLE_COUNT NUMBER := 0;
    BEGIN
        SELECT COUNT(*)
          INTO V_TABLE_COUNT
          FROM USER_TABLES
         WHERE TABLE_NAME = P_TABLE_NAME;
        IF V_TABLE_COUNT = 0 THEN
            DBMS_OUTPUT.PUT_LINE('SKIPPED NON-TABLE OR MISSING OBJECT ' || P_TABLE_NAME);
            RETURN;
        END IF;
        EXECUTE IMMEDIATE 'DELETE FROM "' || P_TABLE_NAME || '"';
        DBMS_OUTPUT.PUT_LINE('CLEARED TABLE ' || P_TABLE_NAME);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                DBMS_OUTPUT.PUT_LINE('SKIPPED MISSING TABLE ' || P_TABLE_NAME);
            ELSE
                RAISE;
            END IF;
    END DELETE_IF_EXISTS;
BEGIN
    IF V_EXPECTED_SCHEMA IS NULL
       OR V_EXPECTED_SCHEMA <> V_SESSION_USER
       OR V_EXPECTED_SCHEMA <> V_CURRENT_SCHEMA THEN
        RAISE_APPLICATION_ERROR(
            -20000
          , '초기화 중단: 실행 인자, SESSION_USER, CURRENT_SCHEMA가 모두 일치해야 합니다.'
        );
    END IF;

    /*
     * 비관리 테이블의 ON DELETE CASCADE/SET NULL이 함께 실행되지 않도록
     * 현재 사용자가 볼 수 있는 외부 FK와 타 스키마 REFERENCES 권한을 차단합니다.
     * REFERENCES는 테이블 권한과 열 단위 권한을 모두 확인합니다.
     */
    SELECT COUNT(*)
      INTO V_EXTERNAL_FK_COUNT
      FROM ALL_CONSTRAINTS FK
      JOIN ALL_CONSTRAINTS PK
        ON PK.OWNER = FK.R_OWNER
       AND PK.CONSTRAINT_NAME = FK.R_CONSTRAINT_NAME
     WHERE 1=1
       AND FK.CONSTRAINT_TYPE = 'R'
       AND PK.OWNER = V_CURRENT_SCHEMA
       AND PK.TABLE_NAME IN (
           'INIT$_TB_PLAN_MONTH', 'INIT$_TB_PLAN_ASSIGNMENT', 'INIT$_TB_PLAN_PROJECT'
         , 'INIT$_TB_PLAN_SCENARIO', 'INIT$_TB_PROJECT_ASSIGNMENT', 'INIT$_TB_PROJECT_COMPANY'
         , 'INIT$_TB_COMPANY_HISTORY', 'INIT$_TB_COMPANY_EMPLOYEE', 'INIT$_TB_NOTICE_FILE'
         , 'INIT$_TB_AUTH_SESSION', 'INIT$_TB_PROJECT', 'INIT$_TB_COMPANY'
         , 'INIT$_TB_SYSTEM_SETTING', 'INIT$_TB_NOTICE', 'INIT$_TB_AI_TRAINING_RUN'
         , 'INIT$_TB_USER'
       )
       AND NOT (
           FK.OWNER = V_CURRENT_SCHEMA
           AND FK.TABLE_NAME IN (
               'INIT$_TB_PLAN_MONTH', 'INIT$_TB_PLAN_ASSIGNMENT', 'INIT$_TB_PLAN_PROJECT'
             , 'INIT$_TB_PLAN_SCENARIO', 'INIT$_TB_PROJECT_ASSIGNMENT', 'INIT$_TB_PROJECT_COMPANY'
             , 'INIT$_TB_COMPANY_HISTORY', 'INIT$_TB_COMPANY_EMPLOYEE', 'INIT$_TB_NOTICE_FILE'
             , 'INIT$_TB_AUTH_SESSION', 'INIT$_TB_PROJECT', 'INIT$_TB_COMPANY'
             , 'INIT$_TB_SYSTEM_SETTING', 'INIT$_TB_NOTICE', 'INIT$_TB_AI_TRAINING_RUN'
             , 'INIT$_TB_USER'
           )
       );

    SELECT COUNT(*)
      INTO V_REFERENCE_GRANT_COUNT
      FROM (
            SELECT GRANTEE
                 , TABLE_NAME
              FROM ALL_TAB_PRIVS
             WHERE TABLE_SCHEMA = V_CURRENT_SCHEMA
               AND PRIVILEGE = 'REFERENCES'
            UNION ALL
            SELECT GRANTEE
                 , TABLE_NAME
              FROM ALL_COL_PRIVS
             WHERE TABLE_SCHEMA = V_CURRENT_SCHEMA
               AND PRIVILEGE = 'REFERENCES'
           )
     WHERE 1=1
       AND GRANTEE <> V_CURRENT_SCHEMA
       AND TABLE_NAME IN (
           'INIT$_TB_PLAN_MONTH', 'INIT$_TB_PLAN_ASSIGNMENT', 'INIT$_TB_PLAN_PROJECT'
         , 'INIT$_TB_PLAN_SCENARIO', 'INIT$_TB_PROJECT_ASSIGNMENT', 'INIT$_TB_PROJECT_COMPANY'
         , 'INIT$_TB_COMPANY_HISTORY', 'INIT$_TB_COMPANY_EMPLOYEE', 'INIT$_TB_NOTICE_FILE'
         , 'INIT$_TB_AUTH_SESSION', 'INIT$_TB_PROJECT', 'INIT$_TB_COMPANY'
         , 'INIT$_TB_SYSTEM_SETTING', 'INIT$_TB_NOTICE', 'INIT$_TB_AI_TRAINING_RUN'
         , 'INIT$_TB_USER'
       );

    IF V_EXTERNAL_FK_COUNT > 0 OR V_REFERENCE_GRANT_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001
          , '초기화 중단: 관리 대상 밖의 FK 또는 타 스키마 REFERENCES 권한이 있습니다.'
        );
    END IF;

    DELETE_IF_EXISTS('INIT$_TB_PLAN_MONTH');
    DELETE_IF_EXISTS('INIT$_TB_PLAN_ASSIGNMENT');
    DELETE_IF_EXISTS('INIT$_TB_PLAN_PROJECT');
    DELETE_IF_EXISTS('INIT$_TB_PLAN_SCENARIO');
    DELETE_IF_EXISTS('INIT$_TB_PROJECT_ASSIGNMENT');
    DELETE_IF_EXISTS('INIT$_TB_PROJECT_COMPANY');
    DELETE_IF_EXISTS('INIT$_TB_COMPANY_HISTORY');
    DELETE_IF_EXISTS('INIT$_TB_COMPANY_EMPLOYEE');
    DELETE_IF_EXISTS('INIT$_TB_NOTICE_FILE');
    DELETE_IF_EXISTS('INIT$_TB_AUTH_SESSION');
    DELETE_IF_EXISTS('INIT$_TB_PROJECT');
    DELETE_IF_EXISTS('INIT$_TB_COMPANY');
    DELETE_IF_EXISTS('INIT$_TB_SYSTEM_SETTING');
    DELETE_IF_EXISTS('INIT$_TB_NOTICE');
    DELETE_IF_EXISTS('INIT$_TB_AI_TRAINING_RUN');
    DELETE_IF_EXISTS('INIT$_TB_USER');
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
UNDEFINE INIT_EXPECTED_SCHEMA
