-- [PLANNING_REFERENCE_PROJECTS]
SELECT P.PROJECT_ID
     , P.PROJECT_YEAR
     , P.PROJECT_NAME
     , P.CUSTOMER_NAME
     , TO_CHAR(P.PROJECT_START_DATE, 'YYYY-MM-DD') AS PROJECT_START_DATE
     , TO_CHAR(P.PROJECT_END_DATE, 'YYYY-MM-DD') AS PROJECT_END_DATE
     , P.ORDER_AMOUNT_VAT
     , P.CONTRACT_AMOUNT_VAT
     , P.STATUS_CODE
 FROM INIT$_TB_PROJECT P
 WHERE 1=1
   AND P.STATUS_CODE <> 'CANCELLED'
   AND P.PROJECT_START_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD')
   AND P.PROJECT_END_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD')
 ORDER BY P.PROJECT_START_DATE
        , P.PROJECT_END_DATE
        , P.PROJECT_NAME
;

-- [PLANNING_REFERENCE_USERS]
SELECT U.USER_ID
     , U.EMPLOYEE_NO
     , U.USER_NAME AS EMPLOYEE_NAME
     , U.DEPARTMENT_NAME
     , U.POSITION_NAME
     , U.JOB_TITLE
     , U.EMAIL
     , U.GENDER_CODE
     , TO_CHAR(U.BIRTH_DATE, 'YYYY-MM-DD') AS BIRTH_DATE
     , U.TECHNICAL_GRADE_CODE
     , U.CAREER_MONTHS
     , U.WORK_LOCATION
     , U.MOBILE_PHONE
     , U.OFFICE_PHONE
     , U.PHOTO_FILE_NAME
     , U.PHOTO_UPDATED_AT
     , U.EMPLOYMENT_TYPE_CODE
     , 'INTERNAL' AS WORKER_TYPE_CODE
     , '인아이티' AS COMPANY_NAME
     , TO_CHAR(U.HIRE_DATE, 'YYYY-MM-DD') AS AVAILABLE_START_DATE
     , TO_CHAR(U.RETIREMENT_DATE, 'YYYY-MM-DD') AS AVAILABLE_END_DATE
 FROM INIT$_TB_USER U
 WHERE 1=1
   AND U.USE_YN = 'Y'
   AND U.EMPLOYMENT_STATUS_CODE <> 'RETIRED'
   AND (U.HIRE_DATE IS NULL OR U.HIRE_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD'))
   AND (U.RETIREMENT_DATE IS NULL OR U.RETIREMENT_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD'))
 ORDER BY U.DEPARTMENT_NAME NULLS LAST
        , U.USER_NAME
;

-- [PLANNING_REFERENCE_COMPANY_EMPLOYEES]
SELECT E.COMPANY_EMPLOYEE_ID
     , E.EMPLOYEE_NO
     , E.EMPLOYEE_NAME
     , E.DEPARTMENT_NAME
     , E.POSITION_NAME
     , E.JOB_TITLE
     , E.EMAIL
     , E.MOBILE_PHONE
     , E.GENDER_CODE
     , E.AGE_YEARS
     , E.TECHNICAL_GRADE_CODE
     , E.CAREER_MONTHS
     , C.COMPANY_TYPE_CODE AS WORKER_TYPE_CODE
     , C.COMPANY_NAME
     , TO_CHAR(E.JOIN_DATE, 'YYYY-MM-DD') AS AVAILABLE_START_DATE
     , TO_CHAR(E.LEAVE_DATE, 'YYYY-MM-DD') AS AVAILABLE_END_DATE
  FROM INIT$_TB_COMPANY_EMPLOYEE E
  JOIN INIT$_TB_COMPANY C
    ON C.COMPANY_ID = E.COMPANY_ID
 WHERE 1=1
   AND E.USE_YN = 'Y'
   AND C.USE_YN = 'Y'
   AND C.COMPANY_TYPE_CODE = 'PARTNER'
   AND (E.JOIN_DATE IS NULL OR E.JOIN_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD'))
   AND (E.LEAVE_DATE IS NULL OR E.LEAVE_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD'))
 ORDER BY C.COMPANY_TYPE_CODE
        , C.COMPANY_NAME
        , E.EMPLOYEE_NAME
;

-- [PLANNING_REFERENCE_ACTUAL_ASSIGNMENTS]
SELECT A.ASSIGNMENT_ID
     , A.USER_ID
     , A.COMPANY_EMPLOYEE_ID
     , NVL(U.USER_NAME, E.EMPLOYEE_NAME) AS EMPLOYEE_NAME
     , A.MONTHLY_ALLOCATION_JSON
  FROM INIT$_TB_PROJECT_ASSIGNMENT A
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = A.PROJECT_ID
  LEFT JOIN INIT$_TB_USER U
    ON U.USER_ID = A.USER_ID
  LEFT JOIN INIT$_TB_COMPANY_EMPLOYEE E
    ON E.COMPANY_EMPLOYEE_ID = A.COMPANY_EMPLOYEE_ID
 WHERE 1=1
   AND P.STATUS_CODE <> 'CANCELLED'
   AND A.ASSIGNMENT_END_DATE >= TO_DATE(TO_CHAR(:planYear) || '0101', 'YYYYMMDD')
   AND A.ASSIGNMENT_START_DATE <= TO_DATE(TO_CHAR(:planYear) || '1231', 'YYYYMMDD')
;

-- [PLANNING_SCENARIO_LIST]
SELECT S.SCENARIO_ID
     , S.PLAN_YEAR
     , S.SCENARIO_NAME
     , S.STATUS_CODE
     , S.REVISION_NO
     , S.DESCRIPTION
     , S.CONFIRMED_AT
     , S.CREATED_AT
     , S.UPDATED_AT
     , (SELECT COUNT(*)
          FROM INIT$_TB_PLAN_PROJECT SP
         WHERE SP.SCENARIO_ID = S.SCENARIO_ID) AS PROJECT_COUNT
     , (SELECT COUNT(*)
          FROM INIT$_TB_PLAN_PROJECT SP
          JOIN INIT$_TB_PLAN_ASSIGNMENT SA
            ON SA.SCENARIO_PROJECT_ID = SP.SCENARIO_PROJECT_ID
         WHERE SP.SCENARIO_ID = S.SCENARIO_ID) AS ASSIGNMENT_COUNT
     , (SELECT NVL(SUM(SA.TOTAL_SALES_AMOUNT), 0)
          FROM INIT$_TB_PLAN_PROJECT SP
          JOIN INIT$_TB_PLAN_ASSIGNMENT SA
            ON SA.SCENARIO_PROJECT_ID = SP.SCENARIO_PROJECT_ID
         WHERE SP.SCENARIO_ID = S.SCENARIO_ID) AS TOTAL_SALES_AMOUNT
     , (SELECT NVL(SUM(SA.TOTAL_COST_AMOUNT), 0)
          FROM INIT$_TB_PLAN_PROJECT SP
          JOIN INIT$_TB_PLAN_ASSIGNMENT SA
            ON SA.SCENARIO_PROJECT_ID = SP.SCENARIO_PROJECT_ID
         WHERE SP.SCENARIO_ID = S.SCENARIO_ID) AS TOTAL_COST_AMOUNT
  FROM INIT$_TB_PLAN_SCENARIO S
 WHERE 1=1
   AND S.PLAN_YEAR = :planYear
 ORDER BY CASE S.STATUS_CODE WHEN 'DRAFT' THEN 1 WHEN 'CONFIRMED' THEN 2 ELSE 3 END
        , NVL(S.UPDATED_AT, S.CREATED_AT) DESC
        , S.SCENARIO_ID DESC
;

-- [PLANNING_SCENARIO_DETAIL]
SELECT S.SCENARIO_ID
     , S.PLAN_YEAR
     , S.SCENARIO_NAME
     , S.STATUS_CODE
     , S.REVISION_NO
     , S.DESCRIPTION
     , S.CONFIRMED_BY
     , S.CONFIRMED_AT
     , S.CREATED_BY
     , S.CREATED_AT
     , S.UPDATED_BY
     , S.UPDATED_AT
  FROM INIT$_TB_PLAN_SCENARIO S
 WHERE 1=1
   AND S.SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_PROJECT_LIST]
SELECT SP.SCENARIO_PROJECT_ID
     , SP.SCENARIO_ID
     , SP.PROJECT_ID
     , P.PROJECT_YEAR
     , P.PROJECT_NAME
     , P.CUSTOMER_NAME
     , P.STATUS_CODE AS PROJECT_STATUS_CODE
     , SP.BID_DECISION_CODE
     , SP.WIN_PROBABILITY
     , TO_CHAR(SP.PLANNED_START_DATE, 'YYYY-MM-DD') AS PLANNED_START_DATE
     , TO_CHAR(SP.PLANNED_END_DATE, 'YYYY-MM-DD') AS PLANNED_END_DATE
     , SP.ANNOUNCEMENT_AMOUNT
     , SP.BID_AMOUNT
     , SP.EXPECTED_CONTRACT_AMOUNT
     , SP.DISCOUNT_RATE
     , SP.SORT_ORDER
     , SP.NOTE
     , SP.TARGET_HEADCOUNT
  FROM INIT$_TB_PLAN_PROJECT SP
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = SP.PROJECT_ID
 WHERE 1=1
   AND SP.SCENARIO_ID = :scenarioId
 ORDER BY SP.SORT_ORDER
        , SP.SCENARIO_PROJECT_ID
;

-- [PLANNING_SCENARIO_ASSIGNMENT_LIST]
SELECT SA.PLAN_ASSIGNMENT_ID
     , SA.SCENARIO_PROJECT_ID
     , SA.USER_ID
     , SA.COMPANY_EMPLOYEE_ID
     , CASE
           WHEN SA.USER_ID IS NOT NULL THEN U.USER_NAME
           ELSE E.EMPLOYEE_NAME
       END AS EMPLOYEE_NAME
     , CASE
           WHEN SA.USER_ID IS NOT NULL THEN U.DEPARTMENT_NAME
           ELSE E.DEPARTMENT_NAME
       END AS DEPARTMENT_NAME
     , CASE
           WHEN SA.USER_ID IS NOT NULL THEN U.POSITION_NAME
           ELSE E.POSITION_NAME
       END AS POSITION_NAME
     , CASE
           WHEN SA.USER_ID IS NOT NULL THEN 'INTERNAL'
           ELSE C.COMPANY_TYPE_CODE
       END AS WORKER_TYPE_CODE
     , CASE
           WHEN SA.USER_ID IS NOT NULL THEN '인아이티'
           ELSE C.COMPANY_NAME
       END AS COMPANY_NAME
     , TO_CHAR(SA.ASSIGNMENT_START_DATE, 'YYYY-MM-DD') AS ASSIGNMENT_START_DATE
     , TO_CHAR(SA.ASSIGNMENT_END_DATE, 'YYYY-MM-DD') AS ASSIGNMENT_END_DATE
     , SA.TOTAL_MM
     , SA.COST_UNIT_PRICE
     , SA.SALES_UNIT_PRICE
     , SA.TOTAL_COST_AMOUNT
     , SA.TOTAL_SALES_AMOUNT
     , SA.OPERATING_PROFIT
     , SA.SORT_ORDER
     , SA.NOTE
     , SA.PROJECT_ROLE_NAME
     , SA.PRIMARY_DUTY
  FROM INIT$_TB_PLAN_ASSIGNMENT SA
  LEFT JOIN INIT$_TB_USER U
    ON U.USER_ID = SA.USER_ID
  LEFT JOIN INIT$_TB_COMPANY_EMPLOYEE E
    ON E.COMPANY_EMPLOYEE_ID = SA.COMPANY_EMPLOYEE_ID
  LEFT JOIN INIT$_TB_COMPANY C
    ON C.COMPANY_ID = E.COMPANY_ID
 WHERE 1=1
   AND SA.SCENARIO_PROJECT_ID IN (
       SELECT SP.SCENARIO_PROJECT_ID
         FROM INIT$_TB_PLAN_PROJECT SP
        WHERE SP.SCENARIO_ID = :scenarioId
   )
 ORDER BY SA.SCENARIO_PROJECT_ID
        , SA.SORT_ORDER
        , SA.PLAN_ASSIGNMENT_ID
;

-- [PLANNING_SCENARIO_MONTH_LIST]
SELECT M.PLAN_MONTH_ID
     , M.PLAN_ASSIGNMENT_ID
     , TO_CHAR(M.ALLOCATION_MONTH, 'YYYY-MM') AS ALLOCATION_MONTH
     , M.MM
     , M.COST_AMOUNT
     , M.SALES_AMOUNT
     , M.OPERATING_PROFIT
  FROM INIT$_TB_PLAN_MONTH M
 WHERE 1=1
   AND M.PLAN_ASSIGNMENT_ID IN (
       SELECT SA.PLAN_ASSIGNMENT_ID
         FROM INIT$_TB_PLAN_ASSIGNMENT SA
         JOIN INIT$_TB_PLAN_PROJECT SP
           ON SP.SCENARIO_PROJECT_ID = SA.SCENARIO_PROJECT_ID
        WHERE SP.SCENARIO_ID = :scenarioId
   )
 ORDER BY M.PLAN_ASSIGNMENT_ID
        , M.ALLOCATION_MONTH
;

-- [PLANNING_SCENARIO_INSERT]
INSERT INTO INIT$_TB_PLAN_SCENARIO (
    PLAN_YEAR
  , SCENARIO_NAME
  , STATUS_CODE
  , REVISION_NO
  , DESCRIPTION
  , CREATED_BY
  , CREATED_AT
) VALUES (
    :planYear
  , :scenarioName
  , 'DRAFT'
  , 1
  , :description
  , :userId
  , SYSTIMESTAMP
)
RETURNING SCENARIO_ID INTO :scenarioIdOut
;

-- [PLANNING_SCENARIO_LOCK]
SELECT S.STATUS_CODE
     , S.REVISION_NO
  FROM INIT$_TB_PLAN_SCENARIO S
 WHERE 1=1
   AND S.SCENARIO_ID = :scenarioId
 FOR UPDATE
;

-- [PLANNING_SCENARIO_REVISION]
SELECT S.REVISION_NO
  FROM INIT$_TB_PLAN_SCENARIO S
 WHERE 1=1
   AND S.SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_UPDATE]
UPDATE INIT$_TB_PLAN_SCENARIO
   SET SCENARIO_NAME = :scenarioName
     , DESCRIPTION = :description
     , REVISION_NO = REVISION_NO + 1
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE 1=1
   AND SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_PROJECT_DELETE_ALL]
DELETE FROM INIT$_TB_PLAN_PROJECT
 WHERE 1=1
   AND SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_PROJECT_INSERT]
INSERT INTO INIT$_TB_PLAN_PROJECT (
    SCENARIO_ID
  , PROJECT_ID
  , BID_DECISION_CODE
  , WIN_PROBABILITY
  , PLANNED_START_DATE
  , PLANNED_END_DATE
  , ANNOUNCEMENT_AMOUNT
  , BID_AMOUNT
  , EXPECTED_CONTRACT_AMOUNT
  , DISCOUNT_RATE
  , SORT_ORDER
  , NOTE
  , CREATED_BY
  , CREATED_AT
  , TARGET_HEADCOUNT
) VALUES (
    :scenarioId
  , :projectId
  , :bidDecisionCode
  , :winProbability
  , :plannedStartDate
  , :plannedEndDate
  , :announcementAmount
  , :bidAmount
  , :expectedContractAmount
  , :discountRate
  , :sortOrder
  , :note
  , :userId
  , SYSTIMESTAMP
  , :targetHeadcount
)
RETURNING SCENARIO_PROJECT_ID INTO :scenarioProjectIdOut
;

-- [PLANNING_SCENARIO_ASSIGNMENT_INSERT]
INSERT INTO INIT$_TB_PLAN_ASSIGNMENT (
    SCENARIO_PROJECT_ID
  , USER_ID
  , COMPANY_EMPLOYEE_ID
  , ASSIGNMENT_START_DATE
  , ASSIGNMENT_END_DATE
  , TOTAL_MM
  , COST_UNIT_PRICE
  , SALES_UNIT_PRICE
  , TOTAL_COST_AMOUNT
  , TOTAL_SALES_AMOUNT
  , OPERATING_PROFIT
  , SORT_ORDER
  , NOTE
  , CREATED_BY
  , CREATED_AT
  , PROJECT_ROLE_NAME
  , PRIMARY_DUTY
) VALUES (
    :scenarioProjectId
  , :employeeUserId
  , :companyEmployeeId
  , :assignmentStartDate
  , :assignmentEndDate
  , :totalMm
  , :costUnitPrice
  , :salesUnitPrice
  , :totalCostAmount
  , :totalSalesAmount
  , :operatingProfit
  , :sortOrder
  , :note
  , :userId
  , SYSTIMESTAMP
  , :projectRoleName
  , :primaryDuty
)
RETURNING PLAN_ASSIGNMENT_ID INTO :planAssignmentIdOut
;

-- [PLANNING_SCENARIO_MONTH_INSERT]
INSERT INTO INIT$_TB_PLAN_MONTH (
    PLAN_ASSIGNMENT_ID
  , ALLOCATION_MONTH
  , MM
  , COST_AMOUNT
  , SALES_AMOUNT
  , OPERATING_PROFIT
) VALUES (
    :planAssignmentId
  , :allocationMonth
  , :mm
  , :costAmount
  , :salesAmount
  , :operatingProfit
)
;

-- [PLANNING_SCENARIO_PROJECT_COUNT]
SELECT COUNT(*)
  FROM INIT$_TB_PLAN_PROJECT SP
 WHERE 1=1
   AND SP.SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_CONFIRM]
UPDATE INIT$_TB_PLAN_SCENARIO
   SET STATUS_CODE = 'CONFIRMED'
     , REVISION_NO = REVISION_NO + 1
     , CONFIRMED_BY = :userId
     , CONFIRMED_AT = SYSTIMESTAMP
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE 1=1
   AND SCENARIO_ID = :scenarioId
;

-- [PLANNING_SCENARIO_DELETE]
DELETE FROM INIT$_TB_PLAN_SCENARIO
 WHERE 1=1
   AND SCENARIO_ID = :scenarioId
   AND STATUS_CODE = 'DRAFT'
   AND REVISION_NO = :revisionNo
;
