-- [PROJECT_ASSIGNMENT_REFERENCE_PROJECTS]
SELECT PROJECT_ID
     , PROJECT_YEAR
     , PROJECT_NAME
     , PROJECT_START_DATE
     , PROJECT_END_DATE
     , CONTRACT_AMOUNT_VAT
  FROM "INIT$_TB_PROJECT"
 WHERE STATUS_CODE <> 'CANCELLED'
 ORDER BY PROJECT_START_DATE DESC
        , PROJECT_END_DATE DESC
        , PROJECT_NAME
;

-- [PROJECT_ASSIGNMENT_REFERENCE_USERS]
SELECT C.COMPANY_ID
     , 'USER' AS WORKER_TYPE_CODE
     , U.USER_ID AS WORKER_ID
     , U.USER_ID
     , CAST(NULL AS NUMBER) AS COMPANY_EMPLOYEE_ID
     , U.EMPLOYEE_NO
     , U.USER_NAME
     , U.DEPARTMENT_NAME
     , U.DEPARTMENT_CODE
     , U.POSITION_NAME
     , U.JOB_TITLE
  FROM "INIT$_TB_COMPANY" C
 CROSS JOIN "INIT$_TB_USER" U
 WHERE 1=1
   AND C.COMPANY_TYPE_CODE = 'HEADQUARTERS'
   AND C.USE_YN = 'Y'
   AND U.USE_YN = 'Y'
   AND U.EMPLOYMENT_STATUS_CODE IN ('ACTIVE', 'LEAVE')
 UNION ALL
SELECT C.COMPANY_ID
     , 'COMPANY_EMPLOYEE' AS WORKER_TYPE_CODE
     , E.COMPANY_EMPLOYEE_ID AS WORKER_ID
     , CAST(NULL AS NUMBER) AS USER_ID
     , E.COMPANY_EMPLOYEE_ID
     , E.EMPLOYEE_NO
     , E.EMPLOYEE_NAME AS USER_NAME
     , E.DEPARTMENT_NAME
     , CAST(NULL AS VARCHAR2(50 BYTE)) AS DEPARTMENT_CODE
     , E.POSITION_NAME
     , E.JOB_TITLE
  FROM "INIT$_TB_COMPANY" C
  JOIN "INIT$_TB_COMPANY_EMPLOYEE" E
    ON E.COMPANY_ID = C.COMPANY_ID
 WHERE 1=1
   AND C.COMPANY_TYPE_CODE = 'PARTNER'
   AND C.USE_YN = 'Y'
   AND E.USE_YN = 'Y'
 ORDER BY COMPANY_ID
        , USER_NAME
        , WORKER_ID
;

-- [PROJECT_ASSIGNMENT_REFERENCE_COMPANIES]
SELECT COMPANY_ID
     , COMPANY_TYPE_CODE
     , COMPANY_NAME
  FROM "INIT$_TB_COMPANY"
 WHERE 1=1
   AND USE_YN = 'Y'
   AND COMPANY_TYPE_CODE IN ('HEADQUARTERS', 'PARTNER')
 ORDER BY CASE COMPANY_TYPE_CODE WHEN 'HEADQUARTERS' THEN 1 WHEN 'PARTNER' THEN 2 ELSE 3 END
        , COMPANY_NAME
;

-- [PROJECT_ASSIGNMENT_MASTER_COMPANY]
SELECT COMPANY_ID
     , COMPANY_TYPE_CODE
     , COMPANY_NAME
  FROM "INIT$_TB_COMPANY"
 WHERE 1=1
   AND COMPANY_ID = :companyId
   AND USE_YN = 'Y'
;

-- [PROJECT_ASSIGNMENT_WORKSPACE_PROJECTS]
SELECT P.PROJECT_ID
     , P.PROJECT_YEAR
     , P.PROJECT_NAME
     , P.CUSTOMER_NAME
     , P.PROJECT_START_DATE
     , P.PROJECT_END_DATE
     , P.CONTRACT_AMOUNT_VAT
     , P.STATUS_CODE
     , COUNT(A.ASSIGNMENT_ID) AS ASSIGNMENT_COUNT
     , NVL(SUM(A.TOTAL_MM), 0) AS TOTAL_MM
  FROM "INIT$_TB_PROJECT" P
  LEFT JOIN "INIT$_TB_PROJECT_ASSIGNMENT" A
    ON A.PROJECT_ID = P.PROJECT_ID
 WHERE 1=1
   AND P.PROJECT_START_DATE <= TO_DATE(TO_CHAR(:projectYear) || '1231', 'YYYYMMDD')
   AND P.PROJECT_END_DATE >= TO_DATE(TO_CHAR(:projectYear) || '0101', 'YYYYMMDD')
   AND P.STATUS_CODE <> 'CANCELLED'
 GROUP BY P.PROJECT_ID
        , P.PROJECT_YEAR
        , P.PROJECT_NAME
        , P.CUSTOMER_NAME
        , P.PROJECT_START_DATE
        , P.PROJECT_END_DATE
        , P.CONTRACT_AMOUNT_VAT
        , P.STATUS_CODE
 ORDER BY P.PROJECT_START_DATE NULLS LAST
        , P.PROJECT_NAME
;

-- [PROJECT_ASSIGNMENT_WORKSPACE_ASSIGNMENTS]
SELECT A.ASSIGNMENT_ID
     , A.PROJECT_ID
     , A.USER_ID
     , A.COMPANY_EMPLOYEE_ID
     , A.PROJECT_COMPANY_ID
     , CASE WHEN A.USER_ID IS NOT NULL THEN 'USER' ELSE 'COMPANY_EMPLOYEE' END AS WORKER_TYPE_CODE
     , NVL(U.USER_NAME, E.EMPLOYEE_NAME) AS EMPLOYEE_NAME
     , CASE
           WHEN A.USER_ID IS NOT NULL THEN '인아이티'
           ELSE NVL(EC.COMPANY_NAME, PC.COMPANY_NAME)
       END AS COMPANY_NAME
     , CASE
           WHEN A.USER_ID IS NOT NULL THEN U.DEPARTMENT_NAME
           ELSE E.DEPARTMENT_NAME
       END AS DEPARTMENT_NAME
     , U.DEPARTMENT_CODE
     , A.ASSIGNMENT_START_DATE
     , A.ASSIGNMENT_END_DATE
     , A.ASSIGNMENT_STATUS_CODE
     , A.ALLOCATION_TYPE_CODE
     , A.DEFAULT_MM
     , A.WEEKLY_DAY_CODES
     , A.TOTAL_MM
     , A.COST_UNIT_PRICE
     , A.SALES_UNIT_PRICE
     , A.OPERATING_PROFIT
     , A.NOTE
     , A.PROJECT_ROLE_NAME
     , A.PRIMARY_DUTY
     , A.DISPLAY_ORDER
     , A.MONTHLY_ALLOCATION_JSON
     , TO_CHAR(NVL(A.UPDATED_AT, A.CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS VERSION_TOKEN
  FROM "INIT$_TB_PROJECT_ASSIGNMENT" A
  JOIN "INIT$_TB_PROJECT" P
    ON P.PROJECT_ID = A.PROJECT_ID
  LEFT JOIN "INIT$_TB_USER" U
    ON U.USER_ID = A.USER_ID
  LEFT JOIN "INIT$_TB_COMPANY_EMPLOYEE" E
    ON E.COMPANY_EMPLOYEE_ID = A.COMPANY_EMPLOYEE_ID
  LEFT JOIN "INIT$_TB_PROJECT_COMPANY" PC
    ON PC.PROJECT_COMPANY_ID = A.PROJECT_COMPANY_ID
  LEFT JOIN "INIT$_TB_COMPANY" EC
    ON EC.COMPANY_ID = E.COMPANY_ID
 WHERE 1=1
   AND P.PROJECT_START_DATE <= TO_DATE(TO_CHAR(:projectYear) || '1231', 'YYYYMMDD')
   AND P.PROJECT_END_DATE >= TO_DATE(TO_CHAR(:projectYear) || '0101', 'YYYYMMDD')
   AND P.STATUS_CODE <> 'CANCELLED'
 ORDER BY A.PROJECT_ID
        , A.DISPLAY_ORDER
        , A.ASSIGNMENT_START_DATE
        , EMPLOYEE_NAME
;

-- [PROJECT_ASSIGNMENT_WORKSPACE_COMPANIES]
SELECT PC.PROJECT_COMPANY_ID
     , PC.PROJECT_ID
     , PC.COMPANY_ID
     , PC.COMPANY_NAME
     , C.COMPANY_TYPE_CODE
     , PC.PARTICIPATION_TYPE_CODE
     , PC.SHARE_RATE
  FROM "INIT$_TB_PROJECT_COMPANY" PC
  JOIN "INIT$_TB_PROJECT" P
    ON P.PROJECT_ID = PC.PROJECT_ID
  LEFT JOIN "INIT$_TB_COMPANY" C
    ON C.COMPANY_ID = PC.COMPANY_ID
 WHERE 1=1
   AND P.PROJECT_START_DATE <= TO_DATE(TO_CHAR(:projectYear) || '1231', 'YYYYMMDD')
   AND P.PROJECT_END_DATE >= TO_DATE(TO_CHAR(:projectYear) || '0101', 'YYYYMMDD')
   AND P.STATUS_CODE <> 'CANCELLED'
 ORDER BY PC.PROJECT_ID
        , PC.PROJECT_COMPANY_ID
;

-- [PROJECT_ASSIGNMENT_PROJECT]
SELECT PROJECT_ID
     , PROJECT_NAME
     , PROJECT_START_DATE
     , PROJECT_END_DATE
     , CONTRACT_AMOUNT_VAT
     , PARTICIPATION_RATE
  FROM "INIT$_TB_PROJECT"
 WHERE 1=1
   AND PROJECT_ID = :projectId
   AND STATUS_CODE <> 'CANCELLED'
;

-- [PROJECT_ASSIGNMENT_PROJECT_LOCK]
SELECT PROJECT_ID
  FROM "INIT$_TB_PROJECT"
 WHERE 1=1
   AND PROJECT_ID = :projectId
   AND STATUS_CODE <> 'CANCELLED'
 FOR UPDATE
;

-- [PROJECT_ASSIGNMENT_COMPANY_LIST]
SELECT C.PROJECT_COMPANY_ID
     , C.PROJECT_ID
     , C.COMPANY_ID
     , C.COMPANY_NAME
     , M.COMPANY_TYPE_CODE
     , C.PARTICIPATION_TYPE_CODE
     , C.SHARE_RATE
     , ROUND(P.CONTRACT_AMOUNT_VAT * C.SHARE_RATE / 100) AS ALLOCATED_SALES_AMOUNT
     , NVL(A.TOTAL_COST_AMOUNT, 0) AS TOTAL_COST_AMOUNT
     , NVL(A.TOTAL_SALES_AMOUNT, 0) AS TOTAL_SALES_AMOUNT
     , NVL(A.OPERATING_PROFIT, 0) AS OPERATING_PROFIT
     , C.NOTE
     , TO_CHAR(NVL(C.UPDATED_AT, C.CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS VERSION_TOKEN
  FROM "INIT$_TB_PROJECT_COMPANY" C
  JOIN "INIT$_TB_PROJECT" P
    ON P.PROJECT_ID = C.PROJECT_ID
  LEFT JOIN "INIT$_TB_COMPANY" M
    ON M.COMPANY_ID = C.COMPANY_ID
  LEFT JOIN (
        SELECT PROJECT_COMPANY_ID
             , SUM(TOTAL_COST_AMOUNT) AS TOTAL_COST_AMOUNT
             , SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
             , SUM(OPERATING_PROFIT) AS OPERATING_PROFIT
          FROM "INIT$_TB_PROJECT_ASSIGNMENT"
         GROUP BY PROJECT_COMPANY_ID
       ) A
    ON A.PROJECT_COMPANY_ID = C.PROJECT_COMPANY_ID
 WHERE C.PROJECT_ID = :projectId
 ORDER BY C.PROJECT_COMPANY_ID
;

-- [PROJECT_ASSIGNMENT_COMPANY_INSERT]
INSERT INTO "INIT$_TB_PROJECT_COMPANY" (
    PROJECT_ID
  , COMPANY_NAME
  , PARTICIPATION_TYPE_CODE
  , SHARE_RATE
  , NOTE
  , CREATED_BY
  , CREATED_AT
  , COMPANY_ID
) VALUES (
    :projectId
  , :companyName
  , :participationTypeCode
  , :shareRate
  , :note
  , :userId
  , SYSTIMESTAMP
  , :companyId
)
RETURNING PROJECT_COMPANY_ID INTO :projectCompanyIdOut
;

-- [PROJECT_ASSIGNMENT_COMPANY_UPDATE]
UPDATE "INIT$_TB_PROJECT_COMPANY"
   SET COMPANY_NAME = :companyName
     , COMPANY_ID = :companyId
     , PARTICIPATION_TYPE_CODE = :participationTypeCode
     , SHARE_RATE = :shareRate
     , NOTE = :note
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
   AND TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') = :versionToken
;

-- [PROJECT_ASSIGNMENT_COMPANY_DELETE]
DELETE FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
   AND TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') = :versionToken
;

-- [PROJECT_ASSIGNMENT_COMPANY_VERSION]
SELECT TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS VERSION_TOKEN
  FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_BELONGS]
SELECT COUNT(*)
  FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_CHANGE_CHECK]
SELECT C.COMPANY_ID
     , COUNT(A.ASSIGNMENT_ID) AS ASSIGNMENT_COUNT
  FROM "INIT$_TB_PROJECT_COMPANY" C
  LEFT JOIN "INIT$_TB_PROJECT_ASSIGNMENT" A
    ON A.PROJECT_COMPANY_ID = C.PROJECT_COMPANY_ID
 WHERE 1=1
   AND C.PROJECT_COMPANY_ID = :projectCompanyId
   AND C.PROJECT_ID = :projectId
 GROUP BY C.COMPANY_ID
;

-- [PROJECT_ASSIGNMENT_PERSON_BELONGS]
SELECT COUNT(*)
  FROM "INIT$_TB_PROJECT_COMPANY" P
 WHERE 1=1
   AND P.PROJECT_COMPANY_ID = :projectCompanyId
   AND P.PROJECT_ID = :projectId
   AND (
        (:employeeUserId IS NOT NULL AND EXISTS (
            SELECT 1
              FROM "INIT$_TB_COMPANY" C
              JOIN "INIT$_TB_USER" U
                ON U.USER_ID = :employeeUserId
             WHERE C.COMPANY_ID = P.COMPANY_ID
               AND C.COMPANY_TYPE_CODE = 'HEADQUARTERS'
               AND C.USE_YN = 'Y'
        ))
        OR
        (:companyEmployeeId IS NOT NULL AND EXISTS (
            SELECT 1
              FROM "INIT$_TB_COMPANY_EMPLOYEE" E
              JOIN "INIT$_TB_COMPANY" C
                ON C.COMPANY_ID = E.COMPANY_ID
             WHERE E.COMPANY_EMPLOYEE_ID = :companyEmployeeId
               AND E.COMPANY_ID = P.COMPANY_ID
               AND C.USE_YN = 'Y'
        ))
       )
;

-- [PROJECT_ASSIGNMENT_COMPANY_OTHER_SHARE]
SELECT NVL(SUM(SHARE_RATE), 0)
  FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_ID = :projectId
   AND (:projectCompanyId IS NULL OR PROJECT_COMPANY_ID <> :projectCompanyId)
;

-- [PROJECT_ASSIGNMENT_LIST]
SELECT A.ASSIGNMENT_ID
     , A.PROJECT_ID
     , A.USER_ID
     , A.COMPANY_EMPLOYEE_ID
     , CASE WHEN A.USER_ID IS NOT NULL THEN 'USER' ELSE 'COMPANY_EMPLOYEE' END AS WORKER_TYPE_CODE
     , NVL(U.EMPLOYEE_NO, E.EMPLOYEE_NO) AS EMPLOYEE_NO
     , NVL(U.USER_NAME, E.EMPLOYEE_NAME) AS USER_NAME
     , NVL(U.DEPARTMENT_NAME, E.DEPARTMENT_NAME) AS DEPARTMENT_NAME
     , U.DEPARTMENT_CODE
     , NVL(U.POSITION_NAME, E.POSITION_NAME) AS POSITION_NAME
     , NVL(U.JOB_TITLE, E.JOB_TITLE) AS JOB_TITLE
     , A.PROJECT_COMPANY_ID
     , C.COMPANY_NAME
     , A.ASSIGNMENT_START_DATE
     , A.ASSIGNMENT_END_DATE
     , A.ASSIGNMENT_STATUS_CODE
     , A.ALLOCATION_TYPE_CODE
     , A.DEFAULT_MM
     , A.WEEKLY_DAY_CODES
     , A.MONTHLY_ALLOCATION_JSON
     , A.TOTAL_MM
     , A.COST_UNIT_PRICE
     , A.SALES_UNIT_PRICE
     , A.TOTAL_COST_AMOUNT
     , A.TOTAL_SALES_AMOUNT
     , A.OPERATING_PROFIT
     , A.NOTE
     , A.PROJECT_ROLE_NAME
     , A.PRIMARY_DUTY
     , A.DISPLAY_ORDER
     , TO_CHAR(NVL(A.UPDATED_AT, A.CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS VERSION_TOKEN
  FROM "INIT$_TB_PROJECT_ASSIGNMENT" A
  LEFT JOIN "INIT$_TB_USER" U
    ON U.USER_ID = A.USER_ID
  LEFT JOIN "INIT$_TB_COMPANY_EMPLOYEE" E
    ON E.COMPANY_EMPLOYEE_ID = A.COMPANY_EMPLOYEE_ID
  LEFT JOIN "INIT$_TB_PROJECT_COMPANY" C
    ON C.PROJECT_COMPANY_ID = A.PROJECT_COMPANY_ID
 WHERE A.PROJECT_ID = :projectId
 ORDER BY A.DISPLAY_ORDER
        , A.ASSIGNMENT_START_DATE
        , U.USER_NAME
        , A.ASSIGNMENT_ID
;

-- [PROJECT_ASSIGNMENT_SUMMARY]
SELECT P.CONTRACT_AMOUNT_VAT
     , NVL(C.COMPANY_SHARE_RATE, 0) AS COMPANY_SHARE_RATE
     , NVL(C.COMPANY_ALLOCATED_AMOUNT, 0) AS COMPANY_ALLOCATED_AMOUNT
     , NVL(A.TOTAL_MM, 0) AS TOTAL_MM
     , NVL(A.TOTAL_COST_AMOUNT, 0) AS TOTAL_COST_AMOUNT
     , NVL(A.TOTAL_SALES_AMOUNT, 0) AS TOTAL_SALES_AMOUNT
     , NVL(A.OPERATING_PROFIT, 0) AS OPERATING_PROFIT
  FROM "INIT$_TB_PROJECT" P
  LEFT JOIN (
        SELECT PROJECT_ID
             , SUM(SHARE_RATE) AS COMPANY_SHARE_RATE
             , SUM(ALLOCATED_AMOUNT) AS COMPANY_ALLOCATED_AMOUNT
          FROM (
                SELECT C.PROJECT_ID
                     , C.SHARE_RATE
                     , ROUND(P2.CONTRACT_AMOUNT_VAT * C.SHARE_RATE / 100) AS ALLOCATED_AMOUNT
                  FROM "INIT$_TB_PROJECT_COMPANY" C
                  JOIN "INIT$_TB_PROJECT" P2
                    ON P2.PROJECT_ID = C.PROJECT_ID
               )
         GROUP BY PROJECT_ID
       ) C
    ON C.PROJECT_ID = P.PROJECT_ID
  LEFT JOIN (
        SELECT PROJECT_ID
             , SUM(TOTAL_MM) AS TOTAL_MM
             , SUM(TOTAL_COST_AMOUNT) AS TOTAL_COST_AMOUNT
             , SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
             , SUM(OPERATING_PROFIT) AS OPERATING_PROFIT
          FROM "INIT$_TB_PROJECT_ASSIGNMENT"
         GROUP BY PROJECT_ID
       ) A
    ON A.PROJECT_ID = P.PROJECT_ID
 WHERE P.PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_INSERT]
INSERT INTO "INIT$_TB_PROJECT_ASSIGNMENT" (
    PROJECT_ID
  , USER_ID
  , PROJECT_COMPANY_ID
  , ASSIGNMENT_START_DATE
  , ASSIGNMENT_END_DATE
  , ASSIGNMENT_STATUS_CODE
  , ALLOCATION_TYPE_CODE
  , DEFAULT_MM
  , WEEKLY_DAY_CODES
  , MONTHLY_ALLOCATION_JSON
  , TOTAL_MM
  , COST_UNIT_PRICE
  , SALES_UNIT_PRICE
  , TOTAL_COST_AMOUNT
  , TOTAL_SALES_AMOUNT
  , OPERATING_PROFIT
  , NOTE
  , CREATED_BY
  , CREATED_AT
  , COMPANY_EMPLOYEE_ID
  , PROJECT_ROLE_NAME
  , PRIMARY_DUTY
  , DISPLAY_ORDER
) VALUES (
    :projectId
  , :employeeUserId
  , :projectCompanyId
  , :assignmentStartDate
  , :assignmentEndDate
  , :assignmentStatusCode
  , :allocationTypeCode
  , :defaultMm
  , :weeklyDayCodes
  , :monthlyAllocationJson
  , :totalMm
  , :costUnitPrice
  , :salesUnitPrice
  , :totalCostAmount
  , :totalSalesAmount
  , :operatingProfit
  , :note
  , :userId
  , SYSTIMESTAMP
  , :companyEmployeeId
  , :projectRoleName
  , :primaryDuty
  , :displayOrder
)
RETURNING ASSIGNMENT_ID INTO :assignmentIdOut
;

-- [PROJECT_ASSIGNMENT_UPDATE]
UPDATE "INIT$_TB_PROJECT_ASSIGNMENT"
   SET USER_ID = :employeeUserId
     , COMPANY_EMPLOYEE_ID = :companyEmployeeId
     , PROJECT_COMPANY_ID = :projectCompanyId
     , ASSIGNMENT_START_DATE = :assignmentStartDate
     , ASSIGNMENT_END_DATE = :assignmentEndDate
     , ASSIGNMENT_STATUS_CODE = :assignmentStatusCode
     , ALLOCATION_TYPE_CODE = :allocationTypeCode
     , DEFAULT_MM = :defaultMm
     , WEEKLY_DAY_CODES = :weeklyDayCodes
     , MONTHLY_ALLOCATION_JSON = :monthlyAllocationJson
     , TOTAL_MM = :totalMm
     , COST_UNIT_PRICE = :costUnitPrice
     , SALES_UNIT_PRICE = :salesUnitPrice
     , TOTAL_COST_AMOUNT = :totalCostAmount
     , TOTAL_SALES_AMOUNT = :totalSalesAmount
     , OPERATING_PROFIT = :operatingProfit
     , NOTE = :note
     , PROJECT_ROLE_NAME = :projectRoleName
     , PRIMARY_DUTY = :primaryDuty
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE ASSIGNMENT_ID = :assignmentId
   AND PROJECT_ID = :projectId
   AND TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') = :versionToken
;

-- [PROJECT_ASSIGNMENT_NEXT_DISPLAY_ORDER]
SELECT NVL(MAX(DISPLAY_ORDER), 0) + 10 AS DISPLAY_ORDER
  FROM "INIT$_TB_PROJECT_ASSIGNMENT"
 WHERE 1=1
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_REORDER]
UPDATE "INIT$_TB_PROJECT_ASSIGNMENT"
   SET DISPLAY_ORDER = :displayOrder
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE 1=1
   AND PROJECT_ID = :projectId
   AND ASSIGNMENT_ID = :assignmentId
;

-- [PROJECT_ASSIGNMENT_COUNT]
SELECT COUNT(*) AS ASSIGNMENT_COUNT
  FROM "INIT$_TB_PROJECT_ASSIGNMENT"
 WHERE 1=1
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_DELETE]
DELETE FROM "INIT$_TB_PROJECT_ASSIGNMENT"
 WHERE ASSIGNMENT_ID = :assignmentId
   AND PROJECT_ID = :projectId
   AND TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') = :versionToken
;

-- [PROJECT_ASSIGNMENT_VERSION]
SELECT TO_CHAR(NVL(UPDATED_AT, CREATED_AT), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS VERSION_TOKEN
  FROM "INIT$_TB_PROJECT_ASSIGNMENT"
 WHERE ASSIGNMENT_ID = :assignmentId
   AND PROJECT_ID = :projectId
;
