-- [WORKFORCE_MANAGEMENT_ESTABLISHMENT_YEAR]
SELECT MIN(
           EXTRACT(
               YEAR FROM COALESCE(
                   C.ESTABLISHED_DATE
                 , H.ESTABLISHED_DATE
               )
           )
       ) AS ESTABLISHMENT_YEAR
  FROM "INIT$_TB_COMPANY" C
  LEFT JOIN (
       SELECT COMPANY_ID
            , MIN(HISTORY_DATE) AS ESTABLISHED_DATE
         FROM "INIT$_TB_COMPANY_HISTORY"
        WHERE 1=1
          AND HISTORY_TYPE_CODE = 'ESTABLISHED'
        GROUP BY COMPANY_ID
       ) H
    ON H.COMPANY_ID = C.COMPANY_ID
 WHERE 1=1
   AND C.COMPANY_TYPE_CODE = 'HEADQUARTERS'
;
